### ISSUE TITLE
support Optional<> for better tri-state boolean

### ISSUE THREAD

**Issue by maxandersen** [remkop/picocli#1108]
currently when you do:

```
@Option(names={"--cds"}, description = "If specified Class Data Sharing (CDS) will be used for building and running (requires Java 13+)", negatable = true)
	Optional<Boolean> cds = Optional.empty();
```

you get:
```
Only boolean options can be negatable, but field java.util.Optional<Boolean> dk.xam.jbang.Main.cds is of type java.util.Optional
picocli.CommandLine$InitializationException: Only boolean options can be negatable, but field java.util.Optional<Boolean> dk.xam.jbang.Main.cds is of type java.util.Optional
	at picocli.CommandLine$Model$CommandSpec.addOptionNegative(CommandLine.java:5585)
	at picocli.CommandLine$Model$CommandSpec.addOption(CommandLine.java:5578)
	at picocli.CommandLine$Model$CommandSpec.add(CommandLine.java:5558)
	at picocli.CommandLine$Model$CommandReflection.initFromAnnotatedTypedMembers(CommandLine.java:10013)
	at picocli.CommandLine$Model$CommandReflection.initFromAnnotatedFields(CommandLine.java:9965)
	at picocli.CommandLine$Model$CommandReflection.extractCommandSpec(CommandLine.java:9898)
	at picocli.CommandLine$Model$CommandSpec.forAnnotatedObject(CommandLine.java:5304)
	at picocli.CommandLine.<init>(CommandLine.java:223)
	at picocli.CommandLine.<init>(CommandLine.java:196)
```

usecase is to be able to use `Optional.isPresent()` to capture when option have not been specified.

**Comment by maxandersen** [comment]
note. currently I simulate it by doing 

```
@Option(names={"--cds"}, description = "If specified Class Data Sharing (CDS) will be used for building and running (requires Java 13+)", negatable = true)
	Boolean cds = null;

Optional<Boolean> cds() { return Optional.ofNullable(cds); }
```

thus just trying to get this directly supported.

**Comment by remkop** [comment]
Interesting idea!

Picocli requires only Java 5, and uses reflection to support APIs that were introduced later, like type converters for `Path` and the `java.time` classes.

That said, it should be possible to support `Optional<T>` for options of type T. Picocli already does something similar with options of type `List<T>` and `Map<K, V>`. 

Any interest in creating a PR for this?

**Comment by remkop** [comment]
The more I think about this the more I like this idea!

**Comment by remkop** [comment]
Expanding the scope of this ticket to also include support for `Map<K, Optional<V>>`.

Unsure whether it is necessary to support `Map<Optional<K>, Optional<V>>` and `Collection<Optional<V>>`.
