### ISSUE TITLE
Exclusive ArgGroup wrongly allows multiple options when using Scope.INHERIT

### ISSUE THREAD

**Issue by quintesse** [remkop/picocli#1182]
We have this in our toplevel command:

```java
	@CommandLine.ArgGroup(exclusive = true)
	Exclusive exclusive = new Exclusive();

	static class Exclusive {
		@Option(names = { "--verbose" },  scope = ScopeType.INHERIT)
		void setVerbose(boolean verbose) {
			Util.setVerbose(verbose);
		}

		@Option(names = { "--quiet" }, scope = ScopeType.INHERIT)
		void setQuiet(boolean quiet) {
			Util.setQuiet(quiet);
		}
	}
```

But unfortunately PicoCli will happily allow specifying multiple versions of these options as long as they are on different sub-commands, eg:

```
java -jar picotest.jar maincmd --verbose subcmd --quiet
```

I assume that's a bug, right?

**Comment by remkop** [comment]
@quintesse, thank you for reporting this!

Not sure if I considered this combination (inherited options and argument groups), and not sure if there are any unit tests to verify correct behavior. 

What should happen if, for example, only one option of a group is marked as inherited?

That said, it looks like I didn’t document this as a restriction and from your example it sounds like there’s no validation to prevent this, so we should either make it work correctly or prevent users from doing this. 

I need some time to look at this.

**Comment by remkop** [comment]
As a workaround, can you try putting the code you showed in a separate class, and using a `@Mixin`-annotated field or method parameter (with this class as its type) in all commands and subcommands where you want to reuse this argument group?

**Comment by quintesse** [comment]
@remkop that gives me:

```
Exception in thread "main" picocli.CommandLine$DuplicateOptionAnnotationsException: Option name '--verbose' is used by both method void dev.jbang.cli.VerboseQuietMixin$Exclusive.setVerbose(boolean) and method void dev.jbang.cli.VerboseQuietMixin$Exclusive.setVerbose(boolean)
	at picocli.CommandLine$DuplicateOptionAnnotationsException.create(CommandLine.java:17132)
	at picocli.CommandLine$DuplicateOptionAnnotationsException.access$2300(CommandLine.java:17126)
	at picocli.CommandLine$Model$CommandSpec.addOption(CommandLine.java:6179)
	at picocli.CommandLine$Model$CommandSpec.addOption(CommandLine.java:6195)
	at picocli.CommandLine$Model$CommandSpec.add(CommandLine.java:6163)
	at picocli.CommandLine$Model$CommandSpec.addGroupArgsToCommand(CommandLine.java:6369)
	at picocli.CommandLine$Model$CommandSpec.addArgGroup(CommandLine.java:6345)
	at picocli.CommandLine$Model$CommandSpec.addMixin(CommandLine.java:6431)
	at picocli.CommandLine$Model$CommandSpec.addMixin(CommandLine.java:6396)
	at picocli.CommandLine$Model$CommandReflection.initFromAnnotatedTypedMembers(CommandLine.java:10822)
	at picocli.CommandLine$Model$CommandReflection.initFromAnnotatedFields(CommandLine.java:10800)
	at picocli.CommandLine$Model$CommandReflection.extractCommandSpec(CommandLine.java:10731)
	at picocli.CommandLine$Model$CommandSpec.forAnnotatedObject(CommandLine.java:5863)
	at picocli.CommandLine.<init>(CommandLine.java:223)
	at picocli.CommandLine.<init>(CommandLine.java:196)
```

**Comment by remkop** [comment]
@quintesse  Can you share your code?

**Comment by quintesse** [comment]
Belay that, I had forgotten to remove the INHERIT options!

**Comment by remkop** [comment]
Ah, yes, I was just going to ask: did you remove the `scope = ScopeType.INHERIT`? Ok then 👍

**Comment by quintesse** [comment]
Ok, so no errors , but it also doesn't work,  It works if you type:

```
java -jar picotest.jar maincmd --verbose --quiet subcmd
```

But not if you type

```
java -jar picotest.jar maincmd --verbose subcmd --quiet
```

TBH I hadn't expected it to work because AFAICT a Mixin would give each (sub)command it's own copy of the Mixin, right? So I'm assuming they don't really know about each other and don't check each other's states?

**Comment by remkop** [comment]
What does "it does not work" mean? Is there an error message? Maybe better to share your code after all... :-)

**Comment by remkop** [comment]
I should read before I type. :anguished:

Thanks for raising this interesting use case. 👍

**Comment by quintesse** [comment]
> Thanks for raising this interesting use case

*mumbles* "Darn users!"

😉

**Comment by remkop** [comment]
Update, copying from #1212:

> Analysis is needed to determine whether it is feasible to support inherited options in argument groups.
> 
> The current syntax allows one option in a group to be inherited, while other options in that same group are _not_ inherited. This will obviously cause problems. 
> 
> One idea to solve this would be to allow `scope = CommandLine.ScopeType.INHERIT` on the argument group. Something like this:
> 
> ```java
> @Command
> class MyCommand {
>     @ArgGroup(heading = " File Output Options%n", scope = CommandLine.ScopeType.INHERIT)
>     OutputOptions outputOptions;
> }
> ```
> 
> The above would then cause the whole group (with all its options, heading, validation settings, etc.) to be inherited by all subcommands of `MyCommand`.
> 
> Thoughts?
>
