### ISSUE TITLE
Another subcommand already exists when using Mockito

### ISSUE THREAD

**Issue by pehala** [remkop/picocli#1243]
### Description
I am using Mockito for testing my commands and I have encountered issue with subcommands.
If you have command that has subcommands and you create `spy()` object of it and pass it to CommandLine it will fail with `picocli.CommandLine$DuplicateNameException: Another subcommand named 'convert' already exists for command 'checksum'`.

### Example
To further demonstrate this problem I have written a small example based on CheckSum example:
**Class:**
```java
package org.example;

import picocli.CommandLine;

import java.io.File;
import java.math.BigInteger;
import java.nio.file.Files;
import java.security.MessageDigest;
import java.util.concurrent.Callable;

/**
 * Hello world!
 *
 */
@CommandLine.Command(name = "checksum",
        mixinStandardHelpOptions = true,
        version = "checksum 4.0",
        description = "Prints the checksum (MD5 by default) of a file to STDOUT.",
        subcommands = SubCommand.class
)
class CheckSum implements Callable<Integer> {

    @CommandLine.Parameters(index = "0", description = "The file whose checksum to calculate.")
    private File file;

    @CommandLine.Option(names = {"-a", "--algorithm"}, description = "MD5, SHA-1, SHA-256, ...")
    private String algorithm = "MD5";

    @Override
    public Integer call() throws Exception { // your business logic goes here...
        byte[] fileContents = Files.readAllBytes(file.toPath());
        byte[] digest = MessageDigest.getInstance(algorithm).digest(fileContents);
        System.out.printf("%0" + (digest.length*2) + "x%n", new BigInteger(1, digest));
        return 0;
    }

    // this example implements Callable, so parsing, error handling and handling user
    // requests for usage help or version help can be done with one line of code.
    public static void main(String... args) {
        int exitCode = new CommandLine(new CheckSum()).execute(args);
        System.exit(exitCode);
    }
}

@CommandLine.Command(name = "convert",
        mixinStandardHelpOptions = true,
        description = "Converts all tracks in the folder into v2 track file versions",
        version = "1.0")
class SubCommand implements Callable<Integer> {

    @Override
    public Integer call() throws Exception {
        return 0;
    }
}
```
**Test:** 
```
package org.example;

import org.junit.jupiter.api.Test;
import picocli.CommandLine;

import static org.mockito.Mockito.spy;

class CheckSumTest {

    @Test
    void testSpy() {
        CheckSum launcher = spy(new CheckSum());

        new CommandLine(launcher);
    }

    @Test
    void testNormal() {
        new CommandLine(new CheckSum());
    }
}
```
**Expected behaviour:**
Both test pass.

**Actual behaviorur:**
`testSpy()` fails

### Versions
* picocli - 4.5.2
* mockito-core - 3.6.0
* mockito-junit-jupiter - 3.6.0
* junit-jupiter-engine - 5.6.2

**Comment by remkop** [comment]
I haven’t tried testing with Mockito...

What do you see when you set system property `picocli.trace` to `DEBUG` before constructing the `CommandLine` instance?

**Comment by pehala** [comment]
```
[picocli DEBUG] Creating CommandSpec for org.example.CheckSum$MockitoMock$1790095900@45fd9a4d with factory picocli.CommandLine$DefaultFactory
[picocli DEBUG] Creating CommandSpec for class org.example.SubCommand with factory picocli.CommandLine$DefaultFactory
[picocli DEBUG] Creating CommandSpec for picocli.CommandLine$AutoHelpMixin@59d2400d with factory picocli.CommandLine$DefaultFactory
[picocli DEBUG] Adding subcommand 'convert' to 'checksum'
[picocli DEBUG] Creating CommandSpec for class org.example.SubCommand with factory picocli.CommandLine$DefaultFactory
[picocli DEBUG] Creating CommandSpec for picocli.CommandLine$AutoHelpMixin@2d1dee39 with factory picocli.CommandLine$DefaultFactory
[picocli DEBUG] Adding subcommand 'convert' to 'checksum'

[picocli DEBUG] Creating CommandSpec for org.example.CheckSum@42f8285e with factory picocli.CommandLine$DefaultFactory
[picocli DEBUG] Creating CommandSpec for class org.example.SubCommand with factory picocli.CommandLine$DefaultFactory
[picocli DEBUG] Creating CommandSpec for picocli.CommandLine$AutoHelpMixin@37052337 with factory picocli.CommandLine$DefaultFactory

picocli.CommandLine$DuplicateNameException: Another subcommand named 'convert' already exists for command 'checksum'

	at picocli.CommandLine$Model$CommandSpec.addSubcommand(CommandLine.java:6070)
	at picocli.CommandLine$Model$CommandReflection.initSubcommands(CommandLine.java:10784)
	at picocli.CommandLine$Model$CommandReflection.extractCommandSpec(CommandLine.java:10745)
	at picocli.CommandLine$Model$CommandSpec.forAnnotatedObject(CommandLine.java:5879)
	at picocli.CommandLine.<init>(CommandLine.java:223)
	at picocli.CommandLine.<init>(CommandLine.java:196)
	at org.example.CheckSumTest.testSpy(CheckSumTest.java:14)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:686)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:212)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:208)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:137)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:71)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:135)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:248)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$5(DefaultLauncher.java:211)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:226)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:199)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:132)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:71)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53)

```

**Comment by pehala** [comment]
It seems to be parsing the command twice due to it being mocked

**Comment by remkop** [comment]
Thanks for the trace debug output!

It looks like there are two 'checksum' command instances, `org.example.CheckSum$MockitoMock$1790095900@45fd9a4d` and `org.example.CheckSum@42f8285e`. This is probably normal with Mockito spy, I am guessing it works a bit like the [tee](https://www.geeksforgeeks.org/tee-command-linux-example/) command in linux.

Because of this, picocli creates two command hierarchies. All commands and subcommands that are duplicates will have the same name, but different object identities. 

We might be able to get it to work if picocli can build up the model by adding subcommands etc. to the _correct_ instance of the parent command. I will need to reproduce this and investigate in more detail.

If you have a sample project in a public repo that would be useful, if not I will try to set one up myself this week.

**Comment by pehala** [comment]
The example can be found in this repository https://github.com/pehala/picocli-mockito-example

**Comment by remkop** [comment]
Great, thank you!  I’ll take a look.

**Comment by remkop** [comment]
Thanks again for the example project!
I was able to reproduce the issue, and it looks like Mockito's spy is a synthetic class (`org.example.CheckSum$MockitoMock$1493359411` - this by itself is not a problem I think), which inherits from the `org.example.CheckSum`, but also contains/duplicates all annotations of the `CheckSum` class.

So, both the mock class and its superclass `CheckSum` have this annotation: 

```
@Command(name="checksum", subcommands=org.example.SubCommand.class,  ...)
```

This, in general is a problem:
Picocli allows [reuse by subclassing](https://picocli.info/#_subclassing), by applying all attributes of the superclass first, and then applying the attributes of the subclass. For the `subcommands` attribute, however, "applying the attribute" means adding subcommands, so the `convert` subcommand ends up being added twice.

For manually written code, the solution is to modify the code such that the `subcommands=org.example.SubCommand.class` annotation exists on either the superclass or on the subclass, but not on both. 

So my first question is, what level of control do we have with Mockito? Is there a Mockito setting to prevent copying the annotations from the superclass onto the synthetic "mock" subclass?

**Comment by pehala** [comment]
We can do that with regular `mock()` (https://javadoc.io/static/org.mockito/mockito-core/3.6.0/org/mockito/MockSettings.html) but I did not find a way to do it with `spy()`.

I have also updated the example project with an additional test that shows how it works with `mock()`.

**Comment by pehala** [comment]
> We can do that with regular `mock()` (https://javadoc.io/static/org.mockito/mockito-core/3.6.0/org/mockito/MockSettings.html) but I did not find a way to do it with `spy()`.
> 
This means that one of the solutions would be to rewrite tests to use `mock()` instead of a `spy()`, problem with that is that I don't how to check that the member variables of the class which are set by picocli and which I am trying to test.

**Comment by remkop** [comment]
That’s great! I’m glad to hear that!

It may be good to add something about this to the user manual. 

Would you like to contribute a section on testing with Mockito to the user manual (`docs/index.adoc`)?

**Comment by pehala** [comment]
I will

**Comment by pehala** [comment]
Thanks a lot for the help!
