### ISSUE TITLE
kotlin nativeImage codegen not working?

### ISSUE THREAD

**Issue by Stefan538871** [remkop/picocli#1306]
Hi, I got 2 applications, 

- java11 + picocli + graal nativeImage https://gitlab.com/Mirakulix/cgoljava
- kotlin + picocli + graal nativeImage https://gitlab.com/Mirakulix/cgolkotlin

apparently nativeImage works flawlessly with Java, but fails on Kotlin with the following exception
```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:291)
	at kotlin.random.Random.<clinit>(Random.kt:272)
	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:351)
	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:271)
	at model.Game.init(Game.kt:13)
	at Application.run(main.kt:46)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at MainKt.main(main.kt:64)
Caused by: java.lang.InstantiationException: Type `kotlin.internal.jdk8.JDK8PlatformImplementations` can not be instantiated reflectively as it does not have a no-parameter constructor or the no-parameter constructor has not been added explicitly to the native image.
	at java.lang.Class.newInstance(DynamicHub.java:850)
	at kotlin.internal.PlatformImplementationsKt.<clinit>(PlatformImplementations.kt:54)
	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:351)
	at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:271)```

I am quite new to Kotlin and graalvm, did i do something wrong or is there a bug in kotlin or kapt?
I could also try to create the required graal reflection files on my own but currently dont know how to do this.

Any help is appreciated, thx in advance

**Comment by remkop** [comment]
Hi @Stefan538871,

There seems to be some problem with this line in `Game.kt`:

```kotlin
                field[x][y] = Random.nextBoolean();
```

This is not a problem of your application or the picocli library, but apparently there is some reflective access that needs to be configured for the Kotlin `Random` class.
This StackOverflow answer may be useful: https://stackoverflow.com/questions/61487173/is-there-a-way-to-use-kotlin-random-random-inside-graalvm-native-image

**Comment by Stefan538871** [comment]
Thank you very much, I replaced Random with ```
        val random = SecureRandom.getInstanceStrong()
        for (x in 0 until field.size) {
            for (y in 0 until field[0].size) {
                field[y][x] = random.nextBoolean()
            }
        }
        ```
        Everything is now working :)

**Comment by remkop** [comment]
Awesome!
Enjoy picocli! 
(And don't forget to give picocli a star ⭐ on GitHub when you get a chance.) 😉
