### ISSUE TITLE
DuplicateOptionAnnotationsException thrown on mixinStandardHelpOptions by picocli-codegen

### ISSUE THREAD

**Issue by charphi** [remkop/picocli#1316]
`DuplicateOptionAnnotationsException` is thrown by picocli-codegen when `mixinStandardHelpOptions` is set to `true` on both a command with scope INHERIT and a subcommand.

Example:
```java
@CommandLine.Command(
        name = "example",
        mixinStandardHelpOptions = true,
        scope = CommandLine.ScopeType.INHERIT,
        subcommands = AutoComplete.GenerateCompletion.class
)
public class Example {
}
```

Stacktrace:
```
[ERROR] FATAL ERROR: picocli.CommandLine$DuplicateOptionAnnotationsException: Option name '-h' is used by both field boolean picocli.CommandLine$AutoHelpMixin.helpRequested and field boolean picocli.CommandLine$AutoHelpMixin.helpRequested
        at picocli.CommandLine$DuplicateOptionAnnotationsException.create(CommandLine.java:17963)
        at picocli.CommandLine$DuplicateOptionAnnotationsException.access$2500(CommandLine.java:17957)
        at picocli.CommandLine$Model$CommandSpec.addOption(CommandLine.java:6572)
        at picocli.CommandLine$Model$CommandSpec.addMixin(CommandLine.java:6818)
        at picocli.CommandLine$Model$CommandSpec.mixinStandardHelpOptions(CommandLine.java:7157)
        at picocli.CommandLine$Model$CommandSpec.mixinStandardHelpOptions(CommandLine.java:7172)
        at picocli.CommandLine$Model$CommandSpec.mixinStandardHelpOptions(CommandLine.java:7172)
        at picocli.codegen.annotation.processing.AbstractCommandSpecProcessor$Context.connectModel(AbstractCommandSpecProcessor.java:922)
        at picocli.codegen.annotation.processing.AbstractCommandSpecProcessor$Context.access$000(AbstractCommandSpecProcessor.java:807)
        at picocli.codegen.annotation.processing.AbstractCommandSpecProcessor.tryProcess(AbstractCommandSpecProcessor.java:194)
        at picocli.codegen.annotation.processing.AbstractCommandSpecProcessor.process(AbstractCommandSpecProcessor.java:165)
```

**Comment by remkop** [comment]
Hi @charphi , this is by design:

putting `scope=INHERIT` on a command means that you don't need to put `mixinStandardHelpOptions = true` on any subcommands any more.

This is documented in the user manual: https://picocli.info/#_inherited_command_attributes

Other options are not inherited.

**Comment by remkop** [comment]
Oh, I see what you mean now; since `GenerateCompletion` is a built-in command, people may expect to be able to combine it with `scope = INHERIT`.

Perhaps we should add a WARN admonition to the [Inherited Command Attributes](https://picocli.info/#_inherited_command_attributes) section that this is a known limitation.

**Comment by remkop** [comment]
Ah wait, I think I understand what you mean (this time for real :rofl: - at least I hope...)

There is an inconsistency: at runtime, the above `Example` class does not throw a DuplicateOptionAnnotationsException; it has some special logic to prevent this error.
However, this special logic is missing from the annotation processor, so at compile time, when the annotation processor is enabled, we are seeing this error.

So, we should fix the annotation processor to not fail on the above `Example` class.

**Comment by remkop** [comment]
I pushed a fix to master. Please verify when you have a chance.

Thinking to release 4.6.2 soon, that includes this fix.

**Comment by charphi** [comment]
I've just tested and it works. Thanks!
