### ISSUE TITLE
picocli-4.6.0.jar requires groovy for OSGi but not for Maven

### ISSUE THREAD

**Issue by Fiouz** [remkop/picocli#1329]
Since 4.6.0, the `META-INF/MANIFEST.MF` file of the [main artifact](https://search.maven.org/artifact/info.picocli/picocli/4.6.0/jar) contains the following line:

```
Import-Package: groovy.lang
```

This does not seem correct as there is a [dedicated artifact](https://search.maven.org/artifact/info.picocli/picocli-groovy/4.6.0/jar) for Groovy support, and, since it does not match the `pom.xml` definition, it confuses consumers that rely on the POM definition to construct their OSGi repository:

```
org.osgi.framework.BundleException: Unable to resolve picocli [3](R 3.0): missing requirement [picocli [3](R 3.0)] osgi.wiring.package; (osgi.wiring.package=groovy.lang) Unresolved requirements: [[picocli [3](R 3.0)] osgi.wiring.package; (osgi.wiring.package=groovy.lang)]
	at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4368)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2281)
	at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:998)
	at aQute.launcher.Launcher.start(Launcher.java:674)
	at aQute.launcher.Launcher.startBundles(Launcher.java:654)
	at aQute.launcher.Launcher.activate(Launcher.java:560)
	at aQute.launcher.Launcher.launch(Launcher.java:400)
	at aQute.launcher.Launcher.run(Launcher.java:181)
	at aQute.launcher.Launcher.main(Launcher.java:157)
	at aQute.launcher.pre.EmbeddedLauncher.executeWithRunPath(EmbeddedLauncher.java:170)
	at aQute.launcher.pre.EmbeddedLauncher.findAndExecute(EmbeddedLauncher.java:135)
	at aQute.launcher.pre.EmbeddedLauncher.main(EmbeddedLauncher.java:52)
```

https://docs.osgi.org/specification/osgi.core/7.0.0/framework.module.html#framework.module.importpackage

**Comment by remkop** [comment]
@Fiouz Thank you for raising this!

I pushed a fix that I believe fixes the issue. Can you verify?

**Comment by Fiouz** [comment]
The change on the current `master` branch fixes the issue, thank you.

**Comment by remkop** [comment]
Thank you for the confirmation! 
And thank you again for raising this! 🙏
