### ISSUE TITLE
Kotlin app: exit code testing using kotest 

### ISSUE THREAD

**Issue by deining** [remkop/picocli#1341]
I tried to use [kotest](https://kotest.io) for exit code testing of my picocli based app coded in Kotlin, with only partial success.

Minimal example:

```
import io.kotest.assertions.throwables.shouldThrow
import io.kotest.core.spec.style.StringSpec
import io.kotest.extensions.system.*
import io.kotest.matchers.shouldBe
import picocli.CommandLine
import picocli.CommandLine.Command
import kotlin.system.exitProcess

class SystemExitTest : StringSpec() {

    // override fun listeners() = listOf(SpecSystemExitListener)

    init {
        "Picocli app should exit process with return code 42" {
            shouldThrow<SystemExitException> {
                CommandLine(PicocliApp()).execute()
            }.exitCode shouldBe 44
        }
    }
}

@Command
class PicocliApp : Runnable {
    override fun run() {
        exitProcess(42)
    }
}
```

The test actually tests two different things:
* `SystemExitException` thrown: seems like this part is fine
* `exit code`: the actual return code is 42, though it should be 44, so the test should fail. For reasons I don't understand the test passes, however.

I don't know whether this is an picocli or an kotest issue. Maybe you are able to shed some light on this. Any help is appreciated.

**Side note**: If I uncomment the override of function `listeners`, the test fails, which is strange, too.

**Comment by remkop** [comment]
> exit code: the actual return code is 42, though it should be 44, so the test should fail. For reasons I don't understand the test passes, however.

Does the test still pass if you change `exitProcess(42)` to another value (either 44 or other values than 42)?
Does the test still pass if you change the expectation `}.exitCode shouldBe 44` to expect a different value?

I don't know whether this is an picocli or an kotest issue.

Does this give the same result?

```kotlin
class SystemExitTest : StringSpec() {
    init {
        "Without picocli: test exit process with return code 42" {
            shouldThrow<SystemExitException> {
                exitProcess(42)
            }.exitCode shouldBe 44
        }
    }
}
```

**Comment by deining** [comment]
> Does this give the same result?

This test works as expected:

```
class SystemExitTestRP : StringSpec() {

    override fun listeners() = listOf(SpecSystemExitListener)

    init {
        "Without picocli: test exit process with return code 42" {
            shouldThrow<SystemExitException> {
                exitProcess(42)
            }.exitCode shouldBe 44
        }
    }
}
```

It fails, and passes if I change the last code line to `.exitCode shouldBe 42`.

This is my test that does **not** work as expected:

```
class SystemExitTest : StringSpec() {

    override fun listeners() = listOf(SpecSystemExitListener)

    init {
        "With picocli app calling system exit process with return code 42" {
            shouldThrow<SystemExitException> {
                CommandLine(PicocliApp()).execute()
            }.exitCode shouldBe 44
        }
    }
}
```

If I run the test with `gradlew test` I'm getting:

```
> Task :test
file or directory 'C:\xxx\build\classes\java\test', not found
Caching disabled for task ':test' because:
  Build cache is disabled
Task ':test' is not up-to-date because:
  Task has failed previously.
file or directory 'C:\xxx\build\classes\java\test', not found
Starting process 'Gradle Test Executor 7'. Working directory: C:\xxx Command: C:\Program Files\Java\jdk-15.0.2\bin\java.exe -Dorg.gradle.native=false @C:\Users\Andreas\AppData\Local\Temp\gradle-worker-classpath3948061195338143899txt -Xmx512m -Dfile.encoding=windows-1252 -Duser.country=DE -Duser.language=de -Duser.variant -ea worker.org.gradle.process.internal.worker.GradleWorkerMain 'Gradle Test Executor 7'
Successfully started process 'Gradle Test Executor 7'

Gradle Test Executor 7 STANDARD_OUT
    ~~~ Kotest Configuration ~~~
    -> Parallelization factor: 1
    -> Concurrent specs: null
    -> Global concurrent tests: 1
    -> Dispatcher affinity: true
    -> Default test timeout: 600000ms
    -> Default test order: Sequential
    -> Default isolation mode: SingleInstance
    -> Global soft assertions: false
    -> Write spec failure file: false
    -> Fail on ignored tests: false
    -> Spec execution order: SpecExecutionOrder
    -> Include test scope affixes: null
    -> Remove test name whitespace: false
    -> Append tags to test names: false
    -> Extensions
      - io.kotest.engine.extensions.SystemPropertyTagExtension
      - io.kotest.core.extensions.RuntimeTagExtension
      - io.kotest.engine.extensions.RuntimeTagExpressionExtension


SystemExitTest > Picocli app should exit process with return code 42 STANDARD_ERROR
    io.kotest.extensions.system.SystemExitException
    	at io.kotest.extensions.system.NoExitSecurityManager.checkExit(SystemExitExtensions.kt:83)
    	at io.kotest.extensions.system.NoExitSecurityManager.checkExit(SystemExitExtensions.kt:81)
    	at java.base/java.lang.Runtime.exit(Runtime.java:113)
    	at java.base/java.lang.System.exit(System.java:1769)
    	at PicocliApp.run(KotestPicoclit.kt:30)
    	at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
    	at picocli.CommandLine.access$1300(CommandLine.java:145)
    	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
    	at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
    	at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
    	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
    	at picocli.CommandLine.execute(CommandLine.java:2078)
    	at SystemExitTest$1.invokeSuspend(KotestPicoclit.kt:17)
    	at SystemExitTest$1.invoke(KotestPicoclit.kt)
    	at io.kotest.core.spec.style.scopes.StringSpecRootScope$invoke$1.invokeSuspend(StringSpecRootScope.kt:58)
    	at io.kotest.core.spec.style.scopes.StringSpecRootScope$invoke$1.invoke(StringSpecRootScope.kt)
    	at io.kotest.core.internal.ExecutionsKt$executeWithBehaviours$2$1.invokeSuspend(executions.kt:13)
    	at io.kotest.core.internal.ExecutionsKt$executeWithBehaviours$2$1.invoke(executions.kt)
    	at io.kotest.core.internal.ExecutionsKt.wrapTestWithGlobalAssert(executions.kt:39)
    	at io.kotest.core.internal.ExecutionsKt$executeWithBehaviours$2.invokeSuspend(executions.kt:12)
    	at io.kotest.core.internal.ExecutionsKt$executeWithBehaviours$2.invoke(executions.kt)
    	at io.kotest.core.internal.ExecutionsKt$wrapTestWithAssertionModeCheck$2.invokeSuspend(executions.kt:25)
    	at io.kotest.core.internal.ExecutionsKt$wrapTestWithAssertionModeCheck$2.invoke(executions.kt)
    	at io.kotest.core.internal.AssertionsCheckKt.executeWithAssertionsCheck(assertionsCheck.kt:25)
    	at io.kotest.core.internal.ExecutionsKt.wrapTestWithAssertionModeCheck(executions.kt:24)
    	at io.kotest.core.internal.ExecutionsKt.executeWithBehaviours(executions.kt:11)
    	at io.kotest.core.internal.TestCaseExecutor$executeInScope$2.invokeSuspend(TestCaseExecutor.kt:266)
    	at io.kotest.core.internal.TestCaseExecutor$executeInScope$2.invoke(TestCaseExecutor.kt)
    	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
    	at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:194)
    	at io.kotest.core.internal.TestCaseExecutor.executeInScope(TestCaseExecutor.kt:260)
    	at io.kotest.core.internal.TestCaseExecutor$executeAndWait$2$1$1$3$1$1.invokeSuspend(TestCaseExecutor.kt:232)
    	at io.kotest.core.internal.TestCaseExecutor$executeAndWait$2$1$1$3$1$1.invoke(TestCaseExecutor.kt)
    	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturnIgnoreTimeout(Undispatched.kt:102)
    	at kotlinx.coroutines.TimeoutKt.setupTimeout(Timeout.kt:148)
    	at kotlinx.coroutines.TimeoutKt.withTimeout(Timeout.kt:44)
    	at io.kotest.core.internal.TestCaseExecutor$executeAndWait$2$1$1$3$1.invokeSuspend(TestCaseExecutor.kt:231)
    	at io.kotest.core.internal.TestCaseExecutor$executeAndWait$2$1$1$3$1.invoke(TestCaseExecutor.kt)
    	at io.kotest.engine.ExecutorExecutionContext$executeWithTimeoutInterruption$3.invokeSuspend(ExecutorExecutionContext.kt:77)
    	at io.kotest.engine.ExecutorExecutionContext$executeWithTimeoutInterruption$3.invoke(ExecutorExecutionContext.kt)
    	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
    	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:165)
    	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
    	at io.kotest.engine.ExecutorExecutionContext.executeWithTimeoutInterruption(ExecutorExecutionContext.kt:75)
    	at io.kotest.core.internal.TestCaseExecutor$executeAndWait$2$1$1$3.invokeSuspend(TestCaseExecutor.kt:230)
    	at io.kotest.core.internal.TestCaseExecutor$executeAndWait$2$1$1$3.invoke(TestCaseExecutor.kt)
    	at io.kotest.mpp.ReplayKt.replay(replay.kt:18)
    	at io.kotest.core.internal.TestCaseExecutor$executeAndWait$2$1$1.invokeSuspend(TestCaseExecutor.kt:225)
    	at io.kotest.core.internal.TestCaseExecutor$executeAndWait$2$1$1.invoke(TestCaseExecutor.kt)
    	at io.kotest.engine.ExecutorExecutionContext$executeWithTimeoutInterruption$3.invokeSuspend(ExecutorExecutionContext.kt:77)
    	at io.kotest.engine.ExecutorExecutionContext$executeWithTimeoutInterruption$3.invoke(ExecutorExecutionContext.kt)
    	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
    	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:165)
    	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
    	at io.kotest.engine.ExecutorExecutionContext.executeWithTimeoutInterruption(ExecutorExecutionContext.kt:75)
    	at io.kotest.core.internal.TestCaseExecutor$executeAndWait$2$1.invokeSuspend(TestCaseExecutor.kt:218)
    	at io.kotest.core.internal.TestCaseExecutor$executeAndWait$2$1.invoke(TestCaseExecutor.kt)
    	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturnIgnoreTimeout(Undispatched.kt:102)
    	at kotlinx.coroutines.TimeoutKt.setupTimeout(Timeout.kt:148)
    	at kotlinx.coroutines.TimeoutKt.withTimeout(Timeout.kt:44)
    	at io.kotest.core.internal.TestCaseExecutor$executeAndWait$2.invokeSuspend(TestCaseExecutor.kt:217)
    	at io.kotest.core.internal.TestCaseExecutor$executeAndWait$2.invoke(TestCaseExecutor.kt)
    	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
    	at kotlinx.coroutines.SupervisorKt.supervisorScope(Supervisor.kt:57)
    	at io.kotest.core.internal.TestCaseExecutor.executeAndWait(TestCaseExecutor.kt:213)
    	at io.kotest.core.internal.TestCaseExecutor.invokeTestCase(TestCaseExecutor.kt:182)
    	at io.kotest.core.internal.TestCaseExecutor.executeActiveTest(TestCaseExecutor.kt:151)
    	at io.kotest.core.internal.TestCaseExecutor$intercept$innerExecute$1$1.invokeSuspend(TestCaseExecutor.kt:89)
    	at io.kotest.core.internal.TestCaseExecutor$intercept$innerExecute$1$1.invoke(TestCaseExecutor.kt)
    	at io.kotest.core.internal.TestCaseExecutor.executeIfActive(TestCaseExecutor.kt:115)
    	at io.kotest.core.internal.TestCaseExecutor$intercept$innerExecute$1.invokeSuspend(TestCaseExecutor.kt:89)
    	at io.kotest.core.internal.TestCaseExecutor$intercept$innerExecute$1.invoke(TestCaseExecutor.kt)
    	at io.kotest.core.internal.TestCaseExecutor.intercept(TestCaseExecutor.kt:103)
    	at io.kotest.core.internal.TestCaseExecutor.execute(TestCaseExecutor.kt:69)
    	at io.kotest.engine.spec.runners.SingleInstanceSpecRunner.runTest(SingleInstanceSpecRunner.kt:106)
    	at io.kotest.engine.spec.runners.SingleInstanceSpecRunner$execute$2$invokeSuspend$$inlined$invoke$lambda$2.invokeSuspend(SingleInstanceSpecRunner.kt:56)
    	at io.kotest.engine.spec.runners.SingleInstanceSpecRunner$execute$2$invokeSuspend$$inlined$invoke$lambda$2.invoke(SingleInstanceSpecRunner.kt)
    	at io.kotest.engine.launchers.SequentialTestLauncher$launch$$inlined$forEach$lambda$1$1.invokeSuspend(SequentialTestLauncher.kt:22)
    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
    	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
    	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
    	at java.base/java.lang.Thread.run(Thread.java:832)

Gradle Test Executor 7 finished executing tests.

> Task :test FAILED

SystemExitTest > Picocli app should exit process with return code 42 FAILED
    java.lang.AssertionError: Expected exception io.kotest.extensions.system.SystemExitException but no exception was thrown.
        at SystemExitTest$1.invokeSuspend(KotestPicoclit.kt:44)
        at SystemExitTest$1.invoke(KotestPicoclit.kt)

        Caused by:
        java.lang.AssertionError: Expected exception io.kotest.extensions.system.SystemExitException but no exception was thrown.
            at SystemExitTest$1.invokeSuspend(KotestPicoclit.kt:44)
            ... 1 more
Finished generating test XML results (0.002 secs) into: C:\xxx\build\test-results\test
Generating HTML test report...
Finished generating test html results (0.004 secs) into: C:\xxx\build\reports\tests\test
:test (Thread[Execution worker for ':' Thread 5,5,main]) completed. Took 3.188 secs.
3 actionable tasks: 1 executed, 2 up-to-date

```

Looks like an SystemExitException is thrown but not considered. Maybe the test task ended prematurely?

**Comment by remkop** [comment]
It’s a bit unusual to exit from the `run` method of a command. The convention is to return an exit code and call `System.exit` from the `main` method with the return value of the `execute` method. 

Would that work as expected?

It’s possible that the test inspects only the top frame of the stack trace.

**Comment by deining** [comment]
> It’s a bit unusual to exit from the `run` method of a command. The convention is to return an exit code and call `System.exit` from the `main` method with the return value of the `execute` method.
> 
> Would that work as expected?

Bingo! Yes, when calling `System.exit` from the `main` method, everything works like expected.
Thanks for your help!

**Comment by remkop** [comment]
Glad I was able to help! 😉

**Comment by deining** [comment]
Following up on our discussion, I opened an [issue](https://github.com/kotest/kotest/issues/2156) in the kotest project. They investigated the case and [suggest](https://github.com/kotest/kotest/issues/2156#issuecomment-792368394) that the reason for the failing test im encountering is the fact that the exception is not rethrown from picocli's `execute` method. Can you have a look and possibly improve that? Thanks.

**Comment by remkop** [comment]
The contract of the `execute` method is that it doesn’t throw any exceptions. 
Any exceptions thrown in the business logic are caught by picocli and passed to the registered ExecutionExceptionHandler. 
Exceptions thrown by this handler result in a stack trace being printed to the standard error stream. 

The `execute` method returns an exit code, it doesn’t throw. 

So that is the picocli side of things. 
What about the Kotlin side of things? I thought you didn’t throw an exception but called `System.exit`?

**Comment by remkop** [comment]
I think this ticket can be closed.
Please let me know if there is any work remaining, I can reopen it. 
:-)
