### ISSUE TITLE
Require additional options based on a given option's value

### ISSUE THREAD

**Issue by sebthom** [remkop/picocli#1374]
Is it possible to declare arg groups in a way that the value of a given option (in my case an enum) controls what other options are required/available.

Something like:

`cmd -a FOO -b <b> -c <c> | -a BAR -d <d> -e <e>`

where the value of `-a` would dictate the possible further options.

**Comment by remkop** [comment]
Hi @sebthom, no, picocli cannot do arg group validation based on option parameter values.

Picocli _would_ be able to do validation if the option itself (not the option parameter, but the option name) is different.
For example:

```
cmd --FOO -b <b> -c <c> | --BAR -d <d> -e <e>
```

For this, picocli would be able to validate the input and print an error message if the user input does not follow this pattern.

If you want the remaining options to depend on the option _parameter_, then you can accomplish this by doing the validation in the application.

**Comment by sebthom** [comment]
Thanks for your response. I am still trying to get my head around it.

So initially I wanted:
```
cmd --auth AD --user <user> --password <value>
  | --auth LDAP --user <value> --password <value> 
  | --auth AWS --access-key <value> --secret-key <value>
```

after your comment I am now trying to get this working:
```
cmd --auth-ad --user <user> --password <value>
  | --auth-ldap --user <value> --password <value> 
  | --auth-aws --access-key <value> --secret-key <value>
```
using:
```java
public class AuthMixin {

   @ArgGroup(exclusive = true, multiplicity = "1")
   AuthOptions authOptions;

   public static class AuthOptions {
      @ArgGroup(exclusive = false, multiplicity = "1")
      ADOption ad;

      @ArgGroup(exclusive = false, multiplicity = "1")
      LDAPOption ldap;

      @ArgGroup(exclusive = false, multiplicity = "1")
      AWSOption aws;
   }

   public static class ADOptions {
      @Option(names = "--auth-ad")
      boolean useActiveDirectory;

      @Option(names = "--user", paramLabel = "USER_NAME")
      String user;

      @Option(names = "--password", paramLabel = "PASSWORD")
      String password;
   }

   public static class LDAPOptions {
      @Option(names = "--auth-ldap")
      boolean useLDAP;

      @Option(names = "--user", paramLabel = "USER_NAME")
      String user;

      @Option(names = "--password", paramLabel = "PASSWORD")
      String password;
   }

   public static class AWSOptions {
      @Option(names = "--auth-aws")
      boolean useLDAP;

      @Option(names = "--access-key", paramLabel = "VALUE")
      String accessKey;

      @Option(names = "--secret-key", paramLabel = "VALUE")
      String secretKey;
   }
}>
```

However I am now getting:
```
Exception in thread "main" picocli.CommandLine$DuplicateNameException: An option cannot be in multiple groups but -u is in ([--auth-ad] [--user=USER_NAME] [--password=PASSWORD]) and ([--auth-ldap] [--user=USER_NAME] [--password=PASSWORD]). Refactor to avoid this. For example, (-a | (-a -b)) can be rewritten as (-a [-b]), and (-a -b | -a -c) can be rewritten as (-a (-b | -c)).
	at picocli.CommandLine$Model$CommandSpec.addGroupArgsToCommand(CommandLine.java:6753)
	at picocli.CommandLine$Model$CommandSpec.addGroupArgsToCommand(CommandLine.java:6764)
	at picocli.CommandLine$Model$CommandSpec.addArgGroup(CommandLine.java:6738)
	at picocli.CommandLine$Model$CommandSpec.addArgGroup(CommandLine.java:6729)
	at picocli.CommandLine$Model$CommandReflection.initFromAnnotatedTypedMembers(CommandLine.java:11502)
	at picocli.CommandLine$Model$CommandReflection.initFromAnnotatedFields(CommandLine.java:11466)
	at picocli.CommandLine$Model$CommandReflection.extractCommandSpec(CommandLine.java:11399)
```

any ideas?

**Comment by remkop** [comment]
Trying to simplify, how about this?

```
cmd ((--ad-user <ad> | --ldap-user <ldap>) 
      --password <pwd>)
    | (--access-key <access> 
       --secret-key <secret>)

```

**Comment by sebthom** [comment]
Based on your suggestion I am now using this:

```java
public class AuthOptionsMixin {

   @ArgGroup(exclusive = true)
   AuthOptions authOptions;

   public static class AuthOptions {
      @ArgGroup(exclusive = false)
      UserPwdADOption userPwd;

      @ArgGroup(exclusive = false)
      AWSOption aws;
   }

   public static class UserPwdOptions {
      static class Directory {
         @Option(names = "--auth-ad")
         public boolean useActiveDirectory;

         @Option(names = "--auth-ldap")
         public boolean useLDAP;
      }

      @ArgGroup(exclusive = true, multiplicity = "1")
      public Directory directory;

      @Option(names = "--user", paramLabel = "USER_NAME")
      String user;

      @Option(names = "--password", paramLabel = "PASSWORD")
      String password;
   }

   public static class AWSOptions {
      @Option(names = "--auth-aws", required = true)
      boolean useLDAP;

      @Option(names = "--access-key", paramLabel = "VALUE")
      String accessKey;

      @Option(names = "--secret-key", paramLabel = "VALUE")
      String secretKey;
   }
}>
```

Is it somehow possible to get rid of the intermediate AuthOptions class, so that I could do something like this?

```java
@ArgGroup(exclusive = true, multiplicity = "1")
public class AuthOptionsMixin {

   @ArgGroup(exclusive = false)
   UserPwdADOption userPwd;

   @ArgGroup(exclusive = false)
   AWSOption aws;

   public static class UserPwdOptions {
      static class Directory {
         @Option(names = "--auth-ad")
         public boolean useActiveDirectory;

         @Option(names = "--auth-ldap")
         public boolean useLDAP;
      }

      @ArgGroup(exclusive = true, multiplicity = "1")
      public Directory directory;

      @Option(names = "--user", paramLabel = "USER_NAME")
      String user;

      @Option(names = "--password", paramLabel = "PASSWORD")
      String password;
   }

   public static class AWSOptions {
      @Option(names = "--auth-aws", required = true)
      boolean useLDAP;

      @Option(names = "--access-key", paramLabel = "VALUE")
      String accessKey;

      @Option(names = "--secret-key", paramLabel = "VALUE")
      String secretKey;
   }
}>
```

If I then declare the mixin in a command like:
```java
@Mixin
AuthOptionsMixin authOptionsMixin;
```

I could then use it like:
```java
if(authOptionsMixin.userPwd.directory.useLDAP) // ...
```
instead of
```java
if(authOptionsMixin.authOptions.userPwd.directory.useLDAP) // ...
```

The more I think about it I feel like it would generally makes sense to allow declaration of the @ArgGroup annotation directly on class level. This could be then used as "default" which can be overriden if required by an @ArgGroup annotation on the field level. WDYT?

**Comment by remkop** [comment]
Hi @sebthom,

it sounds like your suggestion would increase convenience in some use cases.
The trade-off would be increased complexity for users in understanding how to use the annotations, where they can be used, what is the default behaviour and what can be overridden etc.

Generally I am not eager to add features for convenience.

At this point it seems that the benefit would be fairly small, the alternative is only slightly more verbose, so I think leaving things as they are is good enough for now.

**Comment by remkop** [comment]
Closing this ticket.
I hope we got to an acceptable solution for your use case. 😅
