### ISSUE TITLE
Programmatic API doesn't accept scala types

### ISSUE THREAD

**Issue by mvillafuertem** [remkop/picocli#1391]
Hi there, 

Take the following contrived example:
 
```scala

object CliApp {

  import picocli.CommandLine
  import picocli.CommandLine.Model.{ CommandSpec, OptionSpec }

  def main(args: Array[String]): Unit = {

    val spec = CommandSpec.create
    spec.addOption(
      OptionSpec
        .builder("-V", "--verbose")
        .build
    )
    spec.addOption(
      OptionSpec
        .builder("-f", "--file")
        .paramLabel("FILES")
        .`type`(classOf[List[_]])
        .auxiliaryTypes(classOf[File]) // this option is of type List<File>
        .description("The files to process")
        .build
    )
    spec.addOption(
      OptionSpec
        .builder("-n", "--num")
        .paramLabel("COUNT")
        .`type`(classOf[Array[Int]])
        .splitRegex(",")
        .description("Comma-separated list of integers")
        .build
    )
    val commandLine = new CommandLine(spec)

    val args2: Array[String] = Array("--verbose", "-f", "file1", "--file=file2", "-n1,2,3")
    val pr                   = commandLine.parseArgs(args2: _*)

    assert(pr.hasMatchedOption("--verbose")) // as specified on command line

    assert(pr.hasMatchedOption("-V")) // other aliases work also

    assert(pr.hasMatchedOption('V')) // single-character alias works too

    assert(pr.hasMatchedOption("verbose")) // and, command name without hyphens

    import java.util
    assert(Array[Int](1, 2, 3) sameElements pr.matchedOptionValue('n', new Array[Int](0)))
  }
}

```

Error

```
Exception in thread "main" picocli.CommandLine$OverwrittenOptionException: option '--file' (FILES) should be specified only once
	at picocli.CommandLine$Interpreter.applyValueToSingleValuedField(CommandLine.java:13734)
	at picocli.CommandLine$Interpreter.applyOption(CommandLine.java:13598)
	at picocli.CommandLine$Interpreter.processStandaloneOption(CommandLine.java:13470)
	at picocli.CommandLine$Interpreter.processArguments(CommandLine.java:13306)
	at picocli.CommandLine$Interpreter.parse(CommandLine.java:13072)
	at picocli.CommandLine$Interpreter.parse(CommandLine.java:13041)
	at picocli.CommandLine$Interpreter.parse(CommandLine.java:12942)
	at picocli.CommandLine.parseArgs(CommandLine.java:1478)

```

**Comment by remkop** [comment]
I think you are right; a multi-value container class needs to either implement `java.util.Collection` or `java.util.Map` in picocli.

I thought that explicitly setting `arity("*")` on the `--file` option would be a way to work around this but looking at that stacktrace again I now see that this will not work. Picocli needs to cast the container object to `java.util.Collection` before it can call `add` on it... 

So if the Scala `List` class does not implement the `Collection` interface, that is not going to work.

Not sure what the best way for you is to deal with this...
One idea is to use a Java List here, or perhaps you can have a custom subclass of Scala List that implements Collection?

**Comment by remkop** [comment]
@mvillafuertem did this answer your question?

**Comment by mvillafuertem** [comment]
@remkop Yes, thanks for your answer. I am using java list as you suggest

**Comment by remkop** [comment]
Great! I’ll close this ticket then.
