### ISSUE TITLE
Executing commands during other commands sometimes causes NPE

### ISSUE THREAD

**Issue by marinier** [remkop/picocli#1405]
I attempted to post about this on SO, [but the community didn't like my question](https://stackoverflow.com/questions/68695694/npe-in-picocli-commandlineparseresultbuilder) :)

Anyway, I'm thinking it might actually be a bug, so perhaps this is more appropriate. This version of my writeup is better anyway :)

Essentially, I have a REPL that includes a "run" command that starts the system. This command stays "alive" while the system is running, but new commands can still be executed. E.g., printing parts of the state of the system while it's running.

Occasionally, I get a NPE from picocli while executing a nested command like this:

```
java.lang.NullPointerException: null
	at picocli.CommandLine$ParseResult$Builder.access$1000(CommandLine.java:12202)
	at picocli.CommandLine$Interpreter.isAnyHelpRequested(CommandLine.java:14205)
	at picocli.CommandLine$Interpreter.parse(CommandLine.java:13092)
	at picocli.CommandLine$Interpreter.parse(CommandLine.java:13041)
	at picocli.CommandLine$Interpreter.parse(CommandLine.java:12942)
	at picocli.CommandLine.parseArgs(CommandLine.java:1478)
	at picocli.AutoComplete.complete(AutoComplete.java:808)
	at org.jsoar.util.commands.SoarCommandCompletion.complete(SoarCommandCompletion.java:39)
	at org.jsoar.debugger.CommandEntryPanel.lambda$6(CommandEntryPanel.java:326)
	at org.jsoar.runtime.ThreadedAgent.lambda$execute$9(ThreadedAgent.java:577)
	at org.jsoar.runtime.ThreadedAgent.lambda$execute$10(ThreadedAgent.java:601)
	at org.jsoar.runtime.ThreadedAgent.lambda$new$0(ThreadedAgent.java:210)
	at org.jsoar.util.events.SoarEventManager.fireEvent(SoarEventManager.java:119)
	at org.jsoar.util.events.SoarEventManager.fireEvent(SoarEventManager.java:97)
	at org.jsoar.kernel.DecisionCycle.do_one_top_level_phase(DecisionCycle.java:278)
	at org.jsoar.kernel.DecisionCycle.runForever(DecisionCycle.java:1021)
	at org.jsoar.kernel.DecisionCycle.runFor(DecisionCycle.java:998)
	at org.jsoar.kernel.Agent.runFor(Agent.java:724)
	at org.jsoar.runtime.ThreadedAgent.lambda$runFor$2(ThreadedAgent.java:378)
	at org.jsoar.runtime.ThreadedAgent.lambda$execute$9(ThreadedAgent.java:577)
	at org.jsoar.runtime.ThreadedAgent.lambda$execute$10(ThreadedAgent.java:601)
	at org.jsoar.runtime.ThreadedAgent.executeInternal(ThreadedAgent.java:557)
	at org.jsoar.runtime.ThreadedAgent.execute(ThreadedAgent.java:597)
	at org.jsoar.runtime.ThreadedAgent.execute(ThreadedAgent.java:576)
	at org.jsoar.runtime.ThreadedAgent.runFor(ThreadedAgent.java:374)
	at org.jsoar.kernel.commands.RunCommand$Run.run(RunCommand.java:97)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at org.jsoar.kernel.commands.Utils.parseAndRun(Utils.java:52)
	at org.jsoar.kernel.commands.Utils.parseAndRun(Utils.java:62)
	at org.jsoar.util.commands.PicocliSoarCommand.execute(PicocliSoarCommand.java:50)
	at org.jsoar.tcl.SoarTclCommandAdapter.cmdProc(SoarTclCommandAdapter.java:67)
	at tcl.lang.Parser.evalObjv(Parser.java:837)
	at tcl.lang.Parser.eval2(Parser.java:1229)
	at tcl.lang.Interp.eval(Interp.java:2361)
	at tcl.lang.Interp.eval(Interp.java:2338)
	at org.jsoar.tcl.SoarTclInterface.eval(SoarTclInterface.java:411)
	at org.jsoar.debugger.CommandLineRunnable.call(CommandLineRunnable.java:41)
	at org.jsoar.debugger.CommandLineRunnable.call(CommandLineRunnable.java:1)
	at org.jsoar.runtime.ThreadedAgent.lambda$execute$10(ThreadedAgent.java:601)
	at org.jsoar.runtime.ThreadedAgent.executeInternal(ThreadedAgent.java:557)
	at org.jsoar.runtime.ThreadedAgent.execute(ThreadedAgent.java:597)
	at org.jsoar.debugger.CommandEntryPanel.lambda$9(CommandEntryPanel.java:436)
	at org.jsoar.runtime.ThreadedAgent.lambda$execute$10(ThreadedAgent.java:601)
	at org.jsoar.runtime.ThreadedAgent$AgentThread.run(ThreadedAgent.java:798)
```

At the bottom of the stack trace is the agent thread of the REPL. It gets a `run` command that is handled by picocli in the middle of the stack trace, resulting in executing `org.jsoar.kernel.commands.RunCommand$Run.run(RunCommand.java:97)`. New runnables/callables that must be executed on the agent thread are checked for periodically and executed during the run as needed.

In this case, what's happening is someone has typed a partial command on the input thread and we are attempting to provide autocompletion candidates for it. As this involves picocli, we execute this on the agent thread, as seen near the top of the stack trace (`picocli.AutoComplete.complete(AutoComplete.java:808)`). However, sometimes (but not all the time), this results in an NPE inside of picocli. (We execute all picocli interactions on the agent thread, as most of them involve the agent which is not inherently thread safe -- that's why it has it's own thread with a queue for submitting interactions.)

Perhaps there is some kind of global state that is being shared across the two picocli commands? Or perhaps I'm doing something wrong in how I'm executing the original command or requesting the autocomplete? I have not observed this issue when not executing the top-level run command as shown in this stack trace, but then I rarely execute commands outside of a top-level run. I also wonder if perhaps the autocompletion is safe to execute on the input thread (which is a swing UI thread), as it isn't actually interacting with the agent, just picocli? But I'm not sure what the thread safety of picocli is.

If it helps, the code for the system is here: https://github.com/soartech/jsoar/tree/maven/jsoar-core (the tcl part is [here](https://github.com/soartech/jsoar/tree/maven/jsoar-tcl), but it's unlikely that's relevant).

**Comment by marinier** [comment]
This does indeed appear to fix the issue! Since it was somewhat intermittent, it'll take some time to be completely convinced that there are no other related issues, but it was not difficult to cause it to happen before, and I have not been able to reproduce yet with this change. Thank you!

**Comment by remkop** [comment]
Glad to hear that! 🎉 😄
