### ISSUE TITLE
generate commands dynamically

### ISSUE THREAD

**Issue by xbsummer** [remkop/picocli#1506]
Hi,
I use picocli and jline3, and now I need to remotely pull a configuration file (json or yaml that contains commands, descriptions, parameters, etc.) after having the main method ran, and then it will dynamically generate commands and parameters based on this file.  is there any way to achieve this requirement?

**Comment by remkop** [comment]
Yes, you can use picocli's [programmatic API](https://picocli.info/picocli-programmatic-api.html) to construct commands with parameters at runtime.

**Comment by xbsummer** [comment]
```java hl_lines="2"
AnsiConsole.systemInstall();
try {
    Supplier<Path> workDir = () -> Paths.get(System.getProperty("user.dir"));
    // set up JLine built-in commands
    Builtins builtins = new Builtins(workDir, null, null);
    builtins.rename(Builtins.Command.TTOP, "top");
    builtins.alias("zle", "widget");
    builtins.alias("bindkey", "keymap");
    // set up picocli commands
    RootCmd commands = RootCmd.getInstance();

    PicocliCommands.PicocliCommandsFactory factory = new PicocliCommands.PicocliCommandsFactory();
    // Or, if you have your own factory, you can chain them like this:
    // MyCustomFactory customFactory = createCustomFactory(); // your application custom factory
    // PicocliCommandsFactory factory = new PicocliCommandsFactory(customFactory); // chain the factories
    CommandLine cmd = new CommandLine(commands, factory);
    CommandLine.Model.CommandSpec spec = CommandLine.Model.CommandSpec.create();
    spec.name("test");
    spec.mixinStandardHelpOptions(true); // usageHelp and versionHelp options
    spec.addOption(CommandLine.Model.OptionSpec.builder("-c", "--count")
            .paramLabel("COUNT")
            .type(int.class)
            .description("number of times to execute").build());
    spec.addPositional(CommandLine.Model.PositionalParamSpec.builder()
            .paramLabel("FILES")
            .type(List.class).auxiliaryTypes(File.class) // List<File>
            .description("The files to process").build());
    CommandLine commandLine = new CommandLine(spec);
    cmd.addSubcommand(commandLine);

    PicocliCommands picocliCommands = new PicocliCommands(cmd);

    Parser parser = new DefaultParser();
    try (Terminal terminal = TerminalBuilder.builder().build()) {
        SystemRegistry systemRegistry = new SystemRegistryImpl(parser, terminal, workDir, null);
        systemRegistry.setCommandRegistries(builtins, picocliCommands);
        systemRegistry.register("help", picocliCommands);

        LineReader reader = LineReaderBuilder.builder()
                .terminal(terminal)
                .completer(systemRegistry.completer())
                .parser(parser)
                .variable(LineReader.LIST_MAX, 50)   // max tab completion candidates
                .build();
        builtins.setLineReader(reader);
        commands.setReader(reader);
        factory.setTerminal(terminal);
        TailTipWidgets widgets = new TailTipWidgets(reader, systemRegistry::commandDescription, 5, TailTipWidgets.TipType.COMPLETER);
        widgets.enable();
        KeyMap<Binding> keyMap = reader.getKeyMaps().get("main");
        keyMap.bind(new Reference("tailtip-toggle"), KeyMap.alt("s"));

        String prompt = "prompt> ";
        // start the shell and process input until the user quits with Ctrl-D
        String line;
        while (true) {
            try {
                systemRegistry.cleanUp();
                line = reader.readLine(prompt, null, (MaskingCallback) null, null);
                systemRegistry.execute(line);
            } catch (UserInterruptException e) {
                // Ignore
            } catch (EndOfFileException e) {
                return;
            } catch (Exception e) {
                systemRegistry.trace(e);
            }
        }
    }
} catch (Throwable t) {
    t.printStackTrace();
    System.exit(0);
} finally {
    AnsiConsole.systemUninstall();
}
```

```log
picocli.CommandLine$ExecutionException: Parsed command (null) is not a Method, Runnable or Callable
	at picocli.CommandLine.executeUserObject(CommandLine.java:1993)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at picocli.shell.jline3.PicocliCommands.invoke(PicocliCommands.java:283)
	at org.jline.console.impl.SystemRegistryImpl.execute(SystemRegistryImpl.java:1122)
	at org.jline.console.impl.SystemRegistryImpl.execute(SystemRegistryImpl.java:1167)
```

I use the example of  picocli's programming API. There's a problem, please take a look

**Comment by remkop** [comment]
To help me reproduce this issue, please tell me what user input triggered the exception.
Also, what does the `RootCmd` class look like?
Also, can we reproduce this issue without JLine?

**Comment by xbsummer** [comment]
CliCommands commands = new CliCommands();

**Comment by xbsummer** [comment]
![image](https://user-images.githubusercontent.com/17465114/145512417-b50b49a5-86fd-40a7-99a3-95691f2ec7fb.png)

There won't be this problem if ```CommandSpec.create()```  changes to ```CommandSpec.wrapWithoutInspection (new Runable() ...)```,
But how can the run method get command parameters?

**Comment by xbsummer** [comment]
```java
package picocli.shell.jline3.example;

import org.fusesource.jansi.AnsiConsole;
import org.jline.console.SystemRegistry;
import org.jline.console.impl.Builtins;
import org.jline.console.impl.SystemRegistryImpl;
import org.jline.keymap.KeyMap;
import org.jline.reader.*;
import org.jline.reader.impl.DefaultParser;
import org.jline.reader.impl.LineReaderImpl;
import org.jline.terminal.Terminal;
import org.jline.terminal.TerminalBuilder;
import org.jline.widget.TailTipWidgets;
import picocli.CommandLine;
import picocli.CommandLine.ArgGroup;
import picocli.CommandLine.Command;
import picocli.CommandLine.Option;
import picocli.CommandLine.ParentCommand;
import picocli.shell.jline3.PicocliCommands;
import picocli.shell.jline3.PicocliCommands.PicocliCommandsFactory;

import java.io.File;
import java.io.PrintWriter;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.List;
import java.util.concurrent.TimeUnit;
import java.util.function.Supplier;

/**
 * Example that demonstrates how to build an interactive shell with JLine3 and picocli.
 * This example requires JLine 3.16+ and picocli 4.4+.
 * <p>
 * The built-in {@code PicocliCommands.ClearScreen} command was introduced in picocli 4.6.
 * </p>
 */
public class Example {

    /**
     * Top-level command that just prints help.
     */
    @Command(name = "",
            description = {
                    "Example interactive shell with completion and autosuggestions. " +
                            "Hit @|magenta <TAB>|@ to see available commands.",
                    "Hit @|magenta ALT-S|@ to toggle tailtips.",
                    ""},
            footer = {"", "Press Ctrl-D to exit."},
            subcommands = {
                    MyCommand.class, PicocliCommands.ClearScreen.class, CommandLine.HelpCommand.class})
    static class CliCommands implements Runnable {
        PrintWriter out;

        CliCommands() {}

        public void setReader(LineReader reader){
            out = reader.getTerminal().writer();
        }

        public void run() {
            out.println(new CommandLine(this).getUsageMessage());
        }
    }

    /**
     * A command with some options to demonstrate completion.
     */
    @Command(name = "cmd", mixinStandardHelpOptions = true, version = "1.0",
            description = {"Command with some options to demonstrate TAB-completion.",
                    " (Note that enum values also get completed.)"},
            subcommands = {Nested.class, CommandLine.HelpCommand.class})
    static class MyCommand implements Runnable {
        @Option(names = {"-v", "--verbose"},
                description = { "Specify multiple -v options to increase verbosity.",
                        "For example, `-v -v -v` or `-vvv`"})
        private boolean[] verbosity = {};

        @ArgGroup(exclusive = false)
        private MyDuration myDuration = new MyDuration();

        static class MyDuration {
            @Option(names = {"-d", "--duration"},
                    description = "The duration quantity.",
                    required = true)
            private int amount;

            @Option(names = {"-u", "--timeUnit"},
                    description = "The duration time unit.",
                    required = true)
            private TimeUnit unit;
        }

        @ParentCommand CliCommands parent;

        public void run() {
            if (verbosity.length > 0) {
                parent.out.printf("Hi there. You asked for %d %s.%n",
                        myDuration.amount, myDuration.unit);
            } else {
                parent.out.println("hi!");
            }
        }
    }

    @Command(name = "nested", mixinStandardHelpOptions = true, subcommands = {CommandLine.HelpCommand.class},
            description = "Hosts more sub-subcommands")
    static class Nested implements Runnable {
        public void run() {
            System.out.println("I'm a nested subcommand. I don't do much, but I have sub-subcommands!");
        }

        @Command(mixinStandardHelpOptions = true, subcommands = {CommandLine.HelpCommand.class},
                description = "Multiplies two numbers.")
        public void multiply(@Option(names = {"-l", "--left"}, required = true) int left,
                             @Option(names = {"-r", "--right"}, required = true) int right) {
            System.out.printf("%d * %d = %d%n", left, right, left * right);
        }

        @Command(mixinStandardHelpOptions = true, subcommands = {CommandLine.HelpCommand.class},
                description = "Adds two numbers.")
        public void add(@Option(names = {"-l", "--left"}, required = true) int left,
                        @Option(names = {"-r", "--right"}, required = true) int right) {
            System.out.printf("%d + %d = %d%n", left, right, left + right);
        }

        @Command(mixinStandardHelpOptions = true, subcommands = {CommandLine.HelpCommand.class},
                description = "Subtracts two numbers.")
        public void subtract(@Option(names = {"-l", "--left"}, required = true) int left,
                             @Option(names = {"-r", "--right"}, required = true) int right) {
            System.out.printf("%d - %d = %d%n", left, right, left - right);
        }
    }

    public static void main(String[] args) {
        AnsiConsole.systemInstall();
        try {
            Supplier<Path> workDir = () -> Paths.get(System.getProperty("user.dir"));
            // set up JLine built-in commands
            Builtins builtins = new Builtins(workDir, null, null);
            builtins.rename(Builtins.Command.TTOP, "top");
            builtins.alias("zle", "widget");
            builtins.alias("bindkey", "keymap");
            // set up picocli commands
            CliCommands commands = new CliCommands();

            PicocliCommandsFactory factory = new PicocliCommandsFactory();
            // Or, if you have your own factory, you can chain them like this:
            // MyCustomFactory customFactory = createCustomFactory(); // your application custom factory
            // PicocliCommandsFactory factory = new PicocliCommandsFactory(customFactory); // chain the factories

            CommandLine cmd = new CommandLine(commands, factory);

            CommandLine.Model.CommandSpec spec = CommandLine.Model.CommandSpec.create();
//            CommandLine.Model.CommandSpec spec = CommandLine.Model.CommandSpec.wrapWithoutInspection(new Runnable() {
//                @Override
//                public void run() {
//                    //How to get parameters such as FILES or -c
//                }
//            });
            spec.name("test");
            spec.mixinStandardHelpOptions(true); // usageHelp and versionHelp options
            spec.addOption(CommandLine.Model.OptionSpec.builder("-c", "--count")
                    .paramLabel("COUNT")
                    .type(int.class)
                    .description("number of times to execute").build());
            spec.addPositional(CommandLine.Model.PositionalParamSpec.builder()
                    .paramLabel("FILES")
                    .type(List.class).auxiliaryTypes(File.class) // List<File>
                    .description("The files to process").build());
            CommandLine commandLine = new CommandLine(spec);
            cmd.addSubcommand(commandLine);

            PicocliCommands picocliCommands = new PicocliCommands(cmd);

            Parser parser = new DefaultParser();
            try (Terminal terminal = TerminalBuilder.builder().build()) {
                SystemRegistry systemRegistry = new SystemRegistryImpl(parser, terminal, workDir, null);
                systemRegistry.setCommandRegistries(builtins, picocliCommands);
                systemRegistry.register("help", picocliCommands);

                LineReader reader = LineReaderBuilder.builder()
                        .terminal(terminal)
                        .completer(systemRegistry.completer())
                        .parser(parser)
                        .variable(LineReader.LIST_MAX, 50)   // max tab completion candidates
                        .build();
                builtins.setLineReader(reader);
                commands.setReader(reader);
                factory.setTerminal(terminal);
                TailTipWidgets widgets = new TailTipWidgets(reader, systemRegistry::commandDescription, 5, TailTipWidgets.TipType.COMPLETER);
                widgets.enable();
                KeyMap<Binding> keyMap = reader.getKeyMaps().get("main");
                keyMap.bind(new Reference("tailtip-toggle"), KeyMap.alt("s"));

                String prompt = "prompt> ";
                String rightPrompt = null;

                // start the shell and process input until the user quits with Ctrl-D
                String line;
                while (true) {
                    try {
                        systemRegistry.cleanUp();
                        line = reader.readLine(prompt, rightPrompt, (MaskingCallback) null, null);
                        systemRegistry.execute(line);
                    } catch (UserInterruptException e) {
                        // Ignore
                    } catch (EndOfFileException e) {
                        return;
                    } catch (Exception e) {
                        systemRegistry.trace(e);
                    }
                }
            }
        } catch (Throwable t) {
            t.printStackTrace();
        } finally {
            AnsiConsole.systemUninstall();
        }
    }
}
```

**Comment by remkop** [comment]
@xbsummer this discussion may be useful: https://github.com/remkop/picocli/discussions/1501

It shows how to inject the `CommandSpec` into your Runnable.

**Comment by xbsummer** [comment]
Thank you, this is helpful.
