### ISSUE TITLE
picocli throws a big StackOverflowError

### ISSUE THREAD

**Issue by zappee** [remkop/picocli#1680]
I am working on a Java CLI application and I get a picocli StackOverflowError.
This is a strange error and really hard to reproduce. I have tried to create a simple class that demonstrates the issue but that is not easy so the best is if you use the original project.

**Steps to reproduce the StackOverflowError:**

```
git clone https://github.com/zappee/portfolio-analyzer.git
cd portfolio-analyzer/
git checkout remotes/origin/feature/portfolio-summary
JAVA_HOME=/usr/lib/jvm/java-18-openjdk-18.0.1.0.10-1.rolling.el7.x86_64
mvn clean package
java -jar target/portfolio-analyzer-0.1.13.jar price -i bb -d COINBASE_PRO -k aa -p aa -e aa
```
**result:**
```
$ java -jar target/portfolio-analyzer-0.1.13.jar price -i bb -d COINBASE_PRO -k aa -p aa -e aa
Exception in thread "main" java.lang.StackOverflowError
	at picocli.CommandLine$ParseResult$GroupMatchContainer.addMatch(CommandLine.java:12517)
	at picocli.CommandLine$ParseResult$GroupMatchContainer.complete(CommandLine.java:12532)
	at picocli.CommandLine$ParseResult$GroupMatchContainer.addMatch(CommandLine.java:12520)
	at picocli.CommandLine$ParseResult$GroupMatchContainer.complete(CommandLine.java:12532)
	at picocli.CommandLine$ParseResult$GroupMatchContainer.addMatch(CommandLine.java:12520)
	at picocli.CommandLine$ParseResult$GroupMatchContainer.complete(CommandLine.java:12532)
	at picocli.CommandLine$ParseResult$GroupMatchContainer.addMatch(CommandLine.java:12520)
	at picocli.CommandLine$ParseResult$GroupMatchContainer.complete(CommandLine.java:12532)
	at picocli.CommandLine$ParseResult$GroupMatchContainer.addMatch(CommandLine.java:12520)
	at picocli.CommandLine$ParseResult$GroupMatchContainer.complete(CommandLine.java:12532)
	at picocli.CommandLine$ParseResult$GroupMatchContainer.addMatch(CommandLine.java:12520)
	at picocli.CommandLine$ParseResult$GroupMatchContainer.complete(CommandLine.java:12532)
	at picocli.CommandLine$ParseResult$GroupMatchContainer.addMatch(CommandLine.java:12520)
	at picocli.CommandLine$ParseResult$GroupMatchContainer.complete(CommandLine.java:12532)
	at picocli.CommandLine$ParseResult$GroupMatchContainer.addMatch(CommandLine.java:12520)
...
```

The picocli works great, the error only appears in this specific use case: `price -i bb -d COINBASE_PRO -k aa -p aa -e aa`
I hope that you can reproduce this error.

**Comment by remkop** [comment]
Thanks for raising this, that doesn't look good!
I'll take a look when I get to my PC.

**Comment by remkop** [comment]
Quick update:
I have been able to reproduce the issue with your project (thank you).
Have not had enough time to look in detail at the cause.

**Comment by zappee** [comment]
Thanks for the update. I re-arranged a little bit the command line interface and that way StackOverflowError dissapeared.

**Comment by remkop** [comment]
Hi @zappee, I finally had a chance to spend some time stepping through this in a debugger.
I think I found the cause:

The `PriceCommand` class has this ArgGroup:

```java
    /**
     * Coinbase PRO API configuration.
     */
    @CommandLine.ArgGroup(
            exclusive = false,
            multiplicity = "0", // <---------------- this is not good
            heading = "%nCoinbase PRO API:%n")
    private final CoinbaseDataSourceArgGroup coinbaseArgGroup = new CoinbaseDataSourceArgGroup();
```

Note the `multiplicity = "0"` value: this means that the group can be specified zero times!
This is not a valid value for the multiplicity range, but picocli unfortunately does not validate this, and gets stuck trying to enforce that constraint...

From the beginning, there are zero matches, so the max multiplicity (zero) is reached, and picocli then gets in an infinite loop...

```
Exception in thread "main" java.lang.StackOverflowError
        at picocli.CommandLine$ParseResult$GroupMatchContainer.isMaxMultiplicityReached(CommandLine.java:12540)
        at picocli.CommandLine$ParseResult$GroupMatchContainer.addMatch(CommandLine.java:12518)
        at picocli.CommandLine$ParseResult$GroupMatchContainer.complete(CommandLine.java:12532)
 ```


Great catch, thank you for raising this!

On the application side, this can be avoided by specifying `multiplicity = "0..1"`, or `multiplicity = "0..*"`, or `multiplicity = "1"` or whatever other non-zero value makes sense for the application.

On the library side, I will look at adding validation for the multiplicity range: it does not make sense to define ArgGroups that can be specified zero times (never) by the user.

Also, there may still be a potential for an infinite loop in that code, even when max multiplicity is larger than zero, I need to investigate that further.

**Comment by zappee** [comment]
Thx for the response. As I remember during the refactor that I did I modified the multiplicity value as well. So maybe this is why the issue has dissapeared. Thx.
