### ISSUE TITLE
how to configure annotation processor when picocli classes are relocated by shadow plugin

### ISSUE THREAD

**Issue by sify21** [remkop/picocli#1907]
I have a gradle based project, and I'm using shadow plugin to create a uber jar, and all third-party classes are relocated.
However, the classnames in `reflect-config.json` aren't changed. For example:
```
  {
    "name" : "picocli.CommandLine$AutoHelpMixin",
    "allDeclaredConstructors" : true,
    "allPublicConstructors" : true,
    "allDeclaredMethods" : true,
    "allPublicMethods" : true,
    "fields" : [
      { "name" : "helpRequested" },
      { "name" : "versionRequested" }
    ]
  }
```
This class has been relocated to `thirdparty.picocli.CommandLine$AutoHelpMixin`, so when I run the native image created by graalvm, this error occurs:
```
Exception in thread "main" thirdparty.picocli.CommandLine$InitializationException: thirdparty.picocli.CommandLine$AutoHelpMixin@787c77a is not a command: it has no @Command, @Option, @Parameters or @Unmatched annotations
	at thirdparty.picocli.CommandLine$Model$CommandReflection.validateCommandSpec(CommandLine.java:11985)
	at thirdparty.picocli.CommandLine$Model$CommandReflection.extractCommandSpec(CommandLine.java:11815)
	at thirdparty.picocli.CommandLine$Model$CommandSpec.forAnnotatedObject(CommandLine.java:6388)
	at thirdparty.picocli.CommandLine$Model$CommandSpec.mixinStandardHelpOptions(CommandLine.java:7382)
	at thirdparty.picocli.CommandLine$Model$CommandReflection.extractCommandSpec(CommandLine.java:11810)
	at thirdparty.picocli.CommandLine$Model$CommandSpec.forAnnotatedObject(CommandLine.java:6388)
	at thirdparty.picocli.CommandLine.<init>(CommandLine.java:230)
	at thirdparty.picocli.CommandLine.<init>(CommandLine.java:224)
	at thirdparty.picocli.CommandLine.<init>(CommandLine.java:199)
```
How can I handle this situation?

**Comment by sify21** [comment]
It seems that using the latest native-build-tools it's not needed to create the uber jar.

**Comment by remkop** [comment]
Awesome, glad you found a solution!
Enjoy picocli! 😊
