### ISSUE TITLE
StringIndexOutOfBoundsException when calling usage with empty command name

### ISSUE THREAD

**Issue by jansohn** [remkop/picocli#200]
If the name attribute of the `@Command` annotation is set to an empty string (or space) and `usage()` is called the following exception is thrown:

    java.lang.StringIndexOutOfBoundsException: String index out of range: -5
    	at java.lang.String.substring(String.java:1931)
    	at picocli.CommandLine$Help.detailedSynopsis(CommandLine.java:2637)
    	at picocli.CommandLine$Help.synopsis(CommandLine.java:2536)
    	at picocli.CommandLine.usage(CommandLine.java:427)
    	at picocli.CommandLine.usage(CommandLine.java:387)
    	at picocli.CommandLine.usage(CommandLine.java:377)

I think it's a valid use case to set the name to an empty string.

**Comment by remkop** [comment]
Thanks for raising this! I was able to reproduce the issue and I'm looking at it now.

**Comment by remkop** [comment]
Fixed in master. Please verify.
Thanks again for raising this!

**Comment by jansohn** [comment]
Works, thanks for fixing this!

**Comment by remkop** [comment]
Thanks for verifying. Will look at #201 next.
