### ISSUE TITLE
Failed to use subcommand CommandLine to execute command

### ISSUE THREAD

**Issue by nodece** [remkop/picocli#2218]
I'm using picocli@4.7.5 with picocli-shell-jline3@4.7.5, I got the following error:
```
prompt> cmd
picocli.CommandLine$ParameterException: NullPointerException: Cannot read field "versionHelpRequested" because "x0" is null while processing argument at or before arg[0] 'nested' in [nested]: java.lang.NullPointerException: Cannot read field "versionHelpRequested" because "x0" is null
	at picocli.CommandLine$ParameterException.create(CommandLine.java:18643)
	at picocli.CommandLine$ParameterException.access$20900(CommandLine.java:18567)
	at picocli.CommandLine$Interpreter.parse(CommandLine.java:13600)
	at picocli.CommandLine$Interpreter.parse(CommandLine.java:13559)
	at picocli.CommandLine$Interpreter.parse(CommandLine.java:13454)
	at picocli.CommandLine.parseArgs(CommandLine.java:1552)
	at picocli.CommandLine.execute(CommandLine.java:2169)
	at org.example.Main.main(Main.java:153)
Caused by: java.lang.NullPointerException: Cannot read field "versionHelpRequested" because "x0" is null
	at picocli.CommandLine$ParseResult$Builder.access$1100(CommandLine.java:12656)
	at picocli.CommandLine$Interpreter.isAnyHelpRequested(CommandLine.java:14801)
	at picocli.CommandLine$Interpreter.parse(CommandLine.java:13611)
	at picocli.CommandLine$Interpreter.processSubcommand(CommandLine.java:13904)
	at picocli.CommandLine$Interpreter.processArguments(CommandLine.java:13800)
	at picocli.CommandLine$Interpreter.parse(CommandLine.java:13591)
	... 5 more
```

It looks like the `CommandLine` of the parent command didn't parse the input args, so this error has been thrown.

The following is my demo:

```java
package org.example;

import java.io.PrintWriter;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.concurrent.TimeUnit;
import java.util.function.Supplier;
import org.jline.console.SystemRegistry;
import org.jline.console.impl.SystemRegistryImpl;
import org.jline.reader.EndOfFileException;
import org.jline.reader.LineReader;
import org.jline.reader.LineReaderBuilder;
import org.jline.reader.MaskingCallback;
import org.jline.reader.Parser;
import org.jline.reader.UserInterruptException;
import org.jline.reader.impl.DefaultParser;
import org.jline.terminal.Terminal;
import org.jline.terminal.TerminalBuilder;
import picocli.CommandLine;
import picocli.CommandLine.ArgGroup;
import picocli.CommandLine.Command;
import picocli.CommandLine.Option;
import picocli.CommandLine.ParentCommand;
import picocli.shell.jline3.PicocliCommands;

/**
 * Example that demonstrates how to build an interactive shell with JLine3 and picocli.
 * This example requires JLine 3.16+ and picocli 4.4+.
 * <p>
 * The built-in {@code PicocliCommands.ClearScreen} command was introduced in picocli 4.6.
 * </p>
 */
public class Main {

    /**
     * Top-level command that just prints help.
     */
    @Command(name = "test")
    static class CliCommands implements Runnable {
        PrintWriter out;

        CliCommands() {
        }

        public void setReader(LineReader reader) {
            out = reader.getTerminal().writer();
        }

        public void run() {
            out.println(new CommandLine(this).getUsageMessage());
        }
    }

    /**
     * A command with some options to demonstrate completion.
     */
    @Command(name = "cmd", mixinStandardHelpOptions = true, version = "1.0",
            description = {"Command with some options to demonstrate TAB-completion.",
                    " (Note that enum values also get completed.)"},
            subcommands = {Nested.class, CommandLine.HelpCommand.class})
    static class MyCommand implements Runnable {
        @Option(names = {"-v", "--verbose"},
                description = {"Specify multiple -v options to increase verbosity.",
                        "For example, `-v -v -v` or `-vvv`"})
        private boolean[] verbosity = {};

        @ArgGroup(exclusive = false)
        private MyDuration myDuration = new MyDuration();

        static class MyDuration {
            @Option(names = {"-d", "--duration"},
                    description = "The duration quantity.",
                    required = true)
            private int amount;

            @Option(names = {"-u", "--timeUnit"},
                    description = "The duration time unit.",
                    required = true)
            private TimeUnit unit;
        }

        @ParentCommand
        CliCommands parent;

        public void run() {
            if (verbosity.length > 0) {
                System.out.println("Hi there. You asked for %d %s.%n");
            } else {
                System.out.println("Hi");
            }
        }
    }

    @Command(name = "nested", mixinStandardHelpOptions = true, subcommands = {CommandLine.HelpCommand.class},
            description = "Hosts more sub-subcommands")
    static class Nested implements Runnable {
        public void run() {
            System.out.println("I'm a nested subcommand. I don't do much, but I have sub-subcommands!");
        }

        @Command(mixinStandardHelpOptions = true, subcommands = {CommandLine.HelpCommand.class},
                description = "Multiplies two numbers.")
        public void multiply(@Option(names = {"-l", "--left"}, required = true) int left,
                             @Option(names = {"-r", "--right"}, required = true) int right) {
            System.out.printf("%d * %d = %d%n", left, right, left * right);
        }

        @Command(mixinStandardHelpOptions = true, subcommands = {CommandLine.HelpCommand.class},
                description = "Adds two numbers.")
        public void add(@Option(names = {"-l", "--left"}, required = true) int left,
                        @Option(names = {"-r", "--right"}, required = true) int right) {
            System.out.printf("%d + %d = %d%n", left, right, left + right);
        }

        @Command(mixinStandardHelpOptions = true, subcommands = {CommandLine.HelpCommand.class},
                description = "Subtracts two numbers.")
        public void subtract(@Option(names = {"-l", "--left"}, required = true) int left,
                             @Option(names = {"-r", "--right"}, required = true) int right) {
            System.out.printf("%d - %d = %d%n", left, right, left - right);
        }
    }

    public static void main(String[] args) {
        try {
            Supplier<Path> workDir = () -> Paths.get(System.getProperty("user.dir"));
            // set up JLine built-in commands
            // set up picocli commands
            CliCommands commands = new CliCommands();
            CommandLine cmd = new CommandLine(commands);
            cmd.addSubcommand("cmd", new MyCommand());
            PicocliCommands picocliCommands = new PicocliCommands(cmd);
            Parser parser = new DefaultParser();
            Terminal terminal = TerminalBuilder.builder().nativeSignals(true).build();

            // Just to do TAB completion.
            SystemRegistry systemRegistry = new SystemRegistryImpl(parser, terminal, workDir, null);
            systemRegistry.setCommandRegistries(picocliCommands);
            systemRegistry.register("help", picocliCommands);

            LineReader reader = LineReaderBuilder.builder()
                    .terminal(terminal)
                    .parser(parser)
                    .completer(systemRegistry.completer())
                    .build();
            String prompt = "prompt> ";
            String rightPrompt = null;
            String line;
            while (true) {
                try {
                    line = reader.readLine(prompt, rightPrompt, (MaskingCallback) null, null);
//                    systemRegistry.execute(line); // OK
                   CommandLine commandLine = cmd.getSubcommands().get("cmd").getCommandSpec().commandLine(); // FAIL
                   commandLine.execute("nested");
                } catch (UserInterruptException e) {
                    // Ignore
                } catch (EndOfFileException e) {
                    return;
                } catch (Exception e) {
                    systemRegistry.trace(e);
                }
            }
        } catch (Throwable t) {
            t.printStackTrace();
        }
    }
}
```

Here I only use `SystemRegistry` to do TAB completion. When executing, I extract the `CommandLine` of the subcommand to execute the command.

Do you have any suggestions?

**Comment by nodece** [comment]
I tried to use the `SystemRegistry#execute` to execute the line, and it works fine.

But I set up the `ExecutionStrategy` in the subcommand(ex: cmd), this strategy wasn't called, why not the picocli doesn't check if the subcommand strategy exists.

**Comment by nodece** [comment]
This is a workaround by using the `preRun` lifecycle:
```java
public class CommanderFactory {
    static class CommandExecutionStrategy implements IExecutionStrategy {
        private int preRun(ParseResult parseResult) {
            Object userObject = parseResult.commandSpec().userObject();
            if (userObject instanceof CommandHook) {
                int exitCode = ((CommandHook) userObject).preRun();
                if (exitCode != 0) {
                    return exitCode;
                }
            }

            if (parseResult.hasSubcommand()) {
                return preRun(parseResult.subcommand());
            }

            return 0;
        }


        @Override
        public int execute(ParseResult parseResult) throws ExecutionException, ParameterException {
            int preRunCode = preRun(parseResult);
            if (preRunCode != 0) {
                return preRunCode;
            }

            return new CommandLine.RunLast().execute(parseResult);
        }
    }

    /**
     * createRootCommanderWithHook is used for the root command, which supports the hook feature.
     * @param object               Command class or object.
     * @param defaultValueProvider Default value provider of command.
     * @return Picocli commander.
     */
    public static CommandLine createRootCommanderWithHook(Object object, IDefaultValueProvider defaultValueProvider) {
        CommandLine commandLine = new CommandLine(object);
        commandLine.setExecutionStrategy(new CommandExecutionStrategy());
        if (defaultValueProvider != null) {
            commandLine.setDefaultValueProvider(defaultValueProvider);
        }
        return commandLine;
    }
}

public interface CommandHook {
    /**
     * The preRun hook is used to execute commands before.
     *
     * @return If the return value is 0, continue to the next stage.
     */
    default int preRun() {
        return 0;
    }
}


@Command(name = "demo", subcommands = {
        Demo.Sub1.class
})
class Demo implements CommandHook {
    @Override
    public int preRun() {
        System.out.println("demo preRun");
        return 0;
    }
    
    @Command(name = "sub1")
    static class Sub1 implements CommandHook, Runnable {
        @Override
        public int preRun() {
            System.out.println("sub1 preRun");
            return 0;
        }

        @Override
        public void run() {
            System.out.println("sub1 run");
        }
    }

    public static void main(String[] args) {
        CommandLine commandLine = CommanderFactory.createRootCommanderWithHook(Demo.class,null);
        commandLine.execute("sub1");
    }
}
```

Log:
```
demo preRun
sub1 preRun
sub1 run

Process finished with exit code 0

```
