### ISSUE TITLE
Processing of clustered short options seems to be broken on HEAD (846ace0).

### ISSUE THREAD

**Issue by RobertZenz** [remkop/picocli#226]
With the latest HEAD (846ace0 as of writing this) processing clustered short options seems to be broken. Assume that I have a Command class with three flags, like this:

```java
private static class Options {
    @Option(names = "-b")
    private boolean buffered = false;

    @Option(names = "-o")
    private boolean overwriteOutput = true;

    @Option(names = "-v")
    private boolean verbose = false;
}
```

With the input of `-bov` the following exception is thrown:

```
Exception in thread "main" picocli.CommandLine$ParameterException: EmptyStackException: null while processing argument at or before arg[0] '-bov' in [-bov]: java.util.EmptyStackException
	at picocli.CommandLine$ParameterException.create(CommandLine.java:4613)
	at picocli.CommandLine$ParameterException.access$0(CommandLine.java:4610)
	at picocli.CommandLine$Interpreter.parse(CommandLine.java:1978)
	at picocli.CommandLine$Interpreter.parse(CommandLine.java:1955)
	at picocli.CommandLine.parse(CommandLine.java:346)
	at picocli.CommandLine.populateCommand(CommandLine.java:327)
	at picocli.FlagsMain.main(FlagsMain.java:72)
Caused by: java.util.EmptyStackException
	at java.util.Stack.peek(Stack.java:102)
	at java.util.Stack.pop(Stack.java:84)
	at picocli.CommandLine$Interpreter.processClusteredShortOptions(CommandLine.java:2172)
	at picocli.CommandLine$Interpreter.processArguments(CommandLine.java:2059)
	at picocli.CommandLine$Interpreter.parse(CommandLine.java:1972)
	... 4 more
```

Form what I can gather, that seems to be because the processing of clustered options is not exiting when there are no more clustered options. I fixed it locally by using the following patch:

```diff
diff --git a/src/main/java/picocli/CommandLine.java b/src/main/java/picocli/CommandLine.java
index 72c6ad9..782e9bd 100644
--- a/src/main/java/picocli/CommandLine.java
+++ b/src/main/java/picocli/CommandLine.java
@@ -2166,7 +2166,7 @@ public class CommandLine {
                     }
                     int consumed = applyOption(field, Option.class, arity, paramAttachedToOption, args, initialized, argDescription);
                     // only return if cluster (and maybe more) was consumed, otherwise continue do-while loop
-                    if (consumed > 0) {
+                    if (consumed > 0 || args.isEmpty()) {
                         return;
                     }
                     cluster = args.pop();
```

But I'm unsure if that is the best option.

**Comment by remkop** [comment]
Nice catch! Your bugfix looks fine to me.
I'll probably do a 2.0.2 release for this fix. Many thanks!

Note to self: add this test:
```
    @Test
    public void testIssue226EmptyStackWithClusteredOptions() {
        class Options {
            @Option(names = "-b")
            private boolean buffered = false;

            @Option(names = "-o")
            private boolean overwriteOutput = true;

            @Option(names = "-v")
            private boolean verbose = false;
        }
        Options options = CommandLine.populateCommand(new Options(), "-bov");
        assertTrue(options.buffered);
        assertFalse(options.overwriteOutput);
        assertTrue(options.verbose);
    }
```

**Comment by remkop** [comment]
FYI, 2.0.2 is available from Maven Central and JCenter now. Thanks again!
