### ISSUE TITLE
Make simplified @files JCommander-compatible 

### ISSUE THREAD

**Issue by triceo** [remkop/picocli#573]
When we did #551 , we forgot about one corner case, and that is empty lines at the end. JCommander accepts files without them, our implementation does not.

**Comment by remkop** [comment]
What is the expected behaviour? Can you provide a failing unit test?

**Comment by remkop** [comment]
I'm planning to do a picocli 3.9 release end of this week, maybe around December 29. Do you think you can provide a failing unit test before then?

**Comment by remkop** [comment]
Thanks for the PR! I'll take a look ASAP.

**Comment by remkop** [comment]
To be honest I had some trouble understanding what the problem was here...

If I apply the PR in #577 and run the tests, I see the `testAtFileSimplified` test fail like this:

```
picocli.CommandLine$UnmatchedArgumentException: Unmatched argument: 

	at picocli.CommandLine$Interpreter.parse(CommandLine.java:7166)
	at picocli.CommandLine$Interpreter.parse(CommandLine.java:7022)
	at picocli.CommandLine.parse(CommandLine.java:824)
	at picocli.CommandLine.populateCommand(CommandLine.java:777)
	at picocli.CommandLineTest.testAtFileSimplified(CommandLineTest.java:2850)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:592)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
```

The reason it fails is that the parser finds an empty String as the last argument. The `AtFileTestingApp` command used in the test only defines named options, and does not define positional parameters. So, if the parser encounters a positional parameter (the empty string) it throws an `UnmatchedArgumentException`. 

This seemed perfectly fine to me, and I did not understand what the problem was until I looked at the JCommander source. It appears that JCommander [drops empty lines](https://github.com/cbeust/jcommander/blob/master/src/main/java/com/beust/jcommander/JCommander.java#L565) in argument files (@-files). This means it is not possible to specify empty string parameters in this format.

So if the goal is to make "simplified at files" behaviour compatible with JCommander, we should drop all empty lines, not just the trailing empty lines. Is this what you have in mind?

**Comment by remkop** [comment]
Ok, I’ll change the behaviour of simplified at files to:

* ignore all empty lines 
* trim the line before checking if it’s a comment line (starting with `#)

That will make the behaviour compatible with JCommander. 

I’m also thinking to introduce API for this:

* `CommandLine.isUseSimplifiedAtFiles`
* `CommandLine.setUseSimplifiedAtFiles`
* `ParserSpec.useSimplifiedAtFiles` getter
* `ParserSpec.useSimplifiedAtFiles` setter

It may make sense to keep the system property but in the documentation mention the API instead and remove mentions of the system property. 

Thoughts?

**Comment by triceo** [comment]
@remkop Sounds good. I appreciate the new API - I never really liked setting things through system properties.

**Comment by remkop** [comment]
The additional API to control simplified @file format has been pushed to master.
Please verify if you have a chance.

**Comment by triceo** [comment]
@remkop I built the latest master a couple minutes ago and verified that the feature works for my use case.

**Comment by remkop** [comment]
Great, thanks for the confirmation!

**Comment by triceo** [comment]
@remkop Thanks for fixing the issue. Looking forward to 3.9.0!
