### ISSUE TITLE
Improve auto-completion generation to consider current state

### ISSUE THREAD

**Issue by bobtiernay-okta** [remkop/picocli#600]
It appears as though the completion script does not take into account the current state of the command line when performing completions on options:

![image](https://user-images.githubusercontent.com/25536705/51091876-b99dc500-175e-11e9-96c7-13373e65606a.png)

This can result in an invalid command line.

**Comment by remkop** [comment]
I’m not sure that I agree:

* the completion script knows which subcommand (and nested sub-subcommand) has been entered and will only suggest completion candidates for this subcommand
* the completion script knows which option has been entered. If this option takes no arguments (boolean flag) it will suggests all options and subcommands for the command again. If the option _does_ take parameters and the option has completion candidates defined (either explicitly or because the option type is an `enum`) then the script will suggest these completion candidates. 
* In your example, the `--debug` option is specified multiple times. It is perfectly valid to specify options multiple times on the command line. Certainly for multi-value options, but strictly speaking also for single value options or boolean flag options.

**Comment by bobtiernay-okta** [comment]
> If this option takes no arguments (boolean flag) it will suggests all options and subcommands for the command again

I'm not understanding why this is desirable.

> It is perfectly valid to specify options multiple times on the command line

In this case it isn't though. I get a command line error. Given that Picocli has the metadata regarding this, I would have thought the autocompletion script could leverage it in this context.

**Comment by remkop** [comment]
Okay, so while some context-sensitivity already exists, it can be improved. 

What is the type of the `--debug` option and what is the error when it is specified multiple times?

I’m thinking that to improve this, the completion script needs to distinguish between multi-value options (which can be specified multiple times) and single-value ones, with the exception that single-values can be specified multiple times when `CommandLine::setOverwrittenOptionsAllowed` has been set to `true`. Let me know if I’m missing something.

**Comment by bobtiernay-okta** [comment]
> What is the type of the `--debug` option and what is the error when it is specified multiple times?

Here's the type:

```java
    @Option(names = "--debug", description = "Enable additional debugging including logging of commands and of dumping stack traces on failure.")
    boolean debug;
```

And here's the full error trace:

```
$ sage --debug --debug
INVALID: picocli.CommandLine$OverwrittenOptionException: option '--debug' (<debug>) should be specified only once
	at picocli.CommandLine$Interpreter.applyValueToSingleValuedField(CommandLine.java:7591)
	at picocli.CommandLine$Interpreter.applyOption(CommandLine.java:7523)
	at picocli.CommandLine$Interpreter.processStandaloneOption(CommandLine.java:7415)
	at picocli.CommandLine$Interpreter.processArguments(CommandLine.java:7324)
	at picocli.CommandLine$Interpreter.parse(CommandLine.java:7195)
	at picocli.CommandLine$Interpreter.parse(CommandLine.java:7085)
	at picocli.CommandLine.parseArgs(CommandLine.java:836)
	at com.okta.sage.cli.runtime.Runner.execute(Runner.java:62)
	at com.okta.sage.cli.runtime.Runner.run(Runner.java:57)
	at com.okta.sage.cli.Main.main(Main.java:17)
```

**Comment by isakovarseniy** [comment]
I have same issue.

**Comment by remkop** [comment]
I’ll try to improve this but there’s a lot of other things I want to work on for picocli 4.0. Things will likely go faster if anyone is able to submit a pull request for this.
