### ISSUE TITLE
If a `@Command`-annotated method is in a class extending a `@Command`-annotated superclass, things break (`another subcommand named [method] already exists for command [command]`)

### ISSUE THREAD

**Issue by PorygonZRocks** [remkop/picocli#619]
Example: 

`SuperClass.java`
```
import picocli.CommandLine.Command;

@Command(name="super")
public class SuperClass implements Runnable {

	@Override
	public void run() {
		// TODO: Implement this method
	}
	
}
```

`SubClass.java`
```
import picocli.CommandLine.Command;

@Command(name="sub")
public class SubClass extends SuperClass {
	
	@Command(name="method")
	public void method() {}
}
```

`Main.java`
```
import picocli.CommandLine;
import picocli.CommandLine.Command;

@Command(name="main", subcommands= {SuperClass.class, SubClass.class})
public class Main implements Runnable {

	@Override
	public void run() {
		// TODO: Implement this method
	}

	public static void main(String[] args) {
		CommandLine.run(new Main(), "");
	}
}
```

The error
```
picocli.CommandLine$InitializationException: Another subcommand named 'method' already exists for command 'sub'
	at picocli.CommandLine$Model$CommandSpec.addSubcommand(CommandLine.java:3697)
	at picocli.CommandLine$Model$CommandSpec.addMethodSubcommands(CommandLine.java:3740)
	at picocli.CommandLine$Model$CommandReflection.initSubcommands(CommandLine.java:5950)
	at picocli.CommandLine$Model$CommandReflection.updateCommandAttributes(CommandLine.java:5930)
	at picocli.CommandLine$Model$CommandReflection.updateCommandAttributes(CommandLine.java:5914)
	at picocli.CommandLine$Model$CommandReflection.extractCommandSpec(CommandLine.java:5884)
	at picocli.CommandLine$Model$CommandSpec.forAnnotatedObject(CommandLine.java:3580)
	at picocli.CommandLine.<init>(CommandLine.java:185)
	at picocli.CommandLine.toCommandLine(CommandLine.java:2254)
	at picocli.CommandLine.access$8300(CommandLine.java:142)
	at picocli.CommandLine$Model$CommandReflection.initSubcommands(CommandLine.java:5937)
	at picocli.CommandLine$Model$CommandReflection.updateCommandAttributes(CommandLine.java:5930)
	at picocli.CommandLine$Model$CommandReflection.updateCommandAttributes(CommandLine.java:5914)
	at picocli.CommandLine$Model$CommandReflection.extractCommandSpec(CommandLine.java:5884)
	at picocli.CommandLine$Model$CommandSpec.forAnnotatedObject(CommandLine.java:3580)
	at picocli.CommandLine.<init>(CommandLine.java:185)
	at picocli.CommandLine.<init>(CommandLine.java:164)
	at picocli.CommandLine.run(CommandLine.java:1863)
	at picocli.CommandLine.run(CommandLine.java:1794)
	at Main.main(Main.java:13)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.aide.ui.build.java.RunJavaActivity$1.run(SourceFile:108)
	at java.lang.Thread.run(Thread.java:764)
```

It works if I remove the `@Command` annotation from `SuperClass`, or it works if I turn `method()` into a class and add it to `SubClass`'s `subcommands`, but not with `SuperClass` being a `@Command` and `method()` being a method.

**Comment by PorygonZRocks** [comment]
If anyone else needs to find a way around this, I figured something out. I moved the annotation from `SuperClass` to an inner class and added `InnerClass` as a mixin. Everything inherits as it should, and annotated methods work.

**Comment by remkop** [comment]
Thank you reporting this! This is a bug: while walking the class hierarchy, picocli should get attributes from the superclass, including `@Command` methods from the superclass, but it instead of looking at the methods of the superclass, it accidentally was getting methods from its own class.

I will have a fix for this soon.

**Comment by remkop** [comment]
I pushed a fix to the `r3.9.x` branch. There was a merge conflict when I tried to integrate this in master which I didn’t have time to resolve now. I’ll merge into master later.

**Comment by remkop** [comment]
Fixed in the master branch as well as the `r3.9.x` branch now.
Please verify.

**Comment by remkop** [comment]
Picocli 3.9.4 with a fix for this issue has been released. Enjoy!
