### ISSUE TITLE
Annotation processor tests fail when run in Japanese environment

### ISSUE THREAD

**Issue by remkop** [remkop/picocli#715]
For example:

```
testCommandWithBundle
Expected a warning containing "Supported source version 'RELEASE_6' from annotation processor 'picocli.annotation.processing.tests", but only found:
注釈プロセッサ'picocli.annotation.processing.tests.CommandSpec2YamlProcessor'から-source '1.8'より小さいソース・バージョン'RELEASE_6'がサポートされています

	at picocli.annotation.processing.tests.AbstractCommandSpecProcessorTest.assertOnlySourceVersionWarning(AbstractCommandSpecProcessorTest.java:171)
	at picocli.annotation.processing.tests.AbstractCommandSpecProcessorTest.testCommandWithBundle(AbstractCommandSpecProcessorTest.java:147)
```

The failing tests are:

AbstractCommandSpecProcessorTest. testCommandWithBundle
AbstractCommandSpecProcessorTest. testCommandWithMixin
AbstractCommandSpecProcessorTest. testGetterMethodOnInterface
AbstractCommandSpecProcessorTest. testSetterMethodOnClass
AbstractCommandSpecProcessorTest. testSubcommands

**Comment by remkop** [comment]
JavaCompiler (actually JavacMessages) caches a resource bundle, so to fix this we must set the locale to English before running the first test:

```
public class AbstractCommandSpecProcessorTest {

    static Locale old;

    @BeforeClass
    public static void beforeClass() {
        old = Locale.getDefault();
        Locale.setDefault(Locale.UK); // #715 get English diagnostic messages
    }

    @AfterClass
    public static void afterClass() {
        Locale.setDefault(old); // #715 get English diagnostic messages
    }
```
