### ISSUE TITLE
Custom `Factory` fails to create collection for `@Option`s

### ISSUE THREAD

**Issue by bobtiernay-okta** [remkop/picocli#784]
Right now, for the following command method option:

```
@Option(names = "--fields", description = "The fields to display", defaultValue = "timestamp,thread,level,className,message,attributes", split = ",", showDefaultValue = ALWAYS) Set<LineField> fields,
```

I'm getting the following exception:
```
INVALID: picocli.CommandLine$ParameterException: ConfigurationException: Guice configuration errors:

1) No implementation for java.util.Set was bound.
  while locating java.util.Set

1 error while processing argument at or before arg[1] 'logs' in [monolith, logs]: com.google.inject.ConfigurationException: Guice configuration errors:

1) No implementation for java.util.Set was bound.
  while locating java.util.Set

1 error
	at picocli.CommandLine$ParameterException.create(CommandLine.java:14971)
	at picocli.CommandLine$ParameterException.access$16700(CommandLine.java:14895)
	at picocli.CommandLine$Interpreter.parse(CommandLine.java:11003)
	at picocli.CommandLine$Interpreter.processArguments(CommandLine.java:11129)
	at picocli.CommandLine$Interpreter.parse(CommandLine.java:10997)
	at picocli.CommandLine$Interpreter.processArguments(CommandLine.java:11129)
	at picocli.CommandLine$Interpreter.parse(CommandLine.java:10997)
	at picocli.CommandLine$Interpreter.parse(CommandLine.java:10888)
	at picocli.CommandLine.parseArgs(CommandLine.java:1271)
	at cli.runtime.Runner.execute(Runner.java:62)
	at cli.runtime.Runner.run(Runner.java:57)
	at cli.Main.main(Main.java:17)
Caused by: com.google.inject.ConfigurationException: Guice configuration errors:

1) No implementation for java.util.Set was bound.
  while locating java.util.Set

1 error
	at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1075)
	at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1034)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1086)
	at cli.runtime.Factory.create(Factory.java:39)
	at picocli.CommandLine$Interpreter.createCollection(CommandLine.java:11950)
	at picocli.CommandLine$Interpreter.applyValuesToCollectionField(CommandLine.java:11709)
	at picocli.CommandLine$Interpreter.applyOption(CommandLine.java:11383)
	at picocli.CommandLine$Interpreter.applyDefault(CommandLine.java:11073)
	at picocli.CommandLine$Interpreter.applyDefaultValues(CommandLine.java:11042)
	at picocli.CommandLine$Interpreter.parse(CommandLine.java:10996)
	... 9 more
```

My `Factory` is pretty simple, which simply delegates to Guice. But since I don't have a component created for options, it fails. This behavior seems to have changed between 3.x and 4.x, but I'm not sure how to resolve for command methods. I was able to fix it for fields by supplying a default field value.

**Comment by remkop** [comment]
You are right.

The recommended way to fix this is to delegate to the picocli default factory if the requested bean cannot be found in the configuration. This is what the built-in [PicocliSpringFactory](https://github.com/remkop/picocli/blob/master/picocli-spring-boot-starter/src/main/java/picocli/spring/PicocliSpringFactory.java#L26) does.

Something like this:

```java
    @Override
    public <K> K create(Class<K> clazz) throws Exception {
        try {
            return getBeanOrCreate(clazz); // ask the dependency injection container
        } catch (Exception e) {
            return CommandLine.defaultFactory().create(clazz); // fallback if missing
        }
    }
```

I tried to track down when the change was made to delegate the creation of `Collection`s to the factory. I believe you are right that this happened around 4.0. There is no separate ticket for this and it was not mentioned in the release notes. It should have been mentioned under potential breaking changes.

I am thinking to update the 4.0 release notes to add this to the list of breaking changes.

I will also update the Guice example to add a try/catch that falls back to the picocli default factory as in the above example.

**Comment by bobtiernay-okta** [comment]
That works, thanks a lot!

**Comment by remkop** [comment]
User manual updated, and added entry to the 4.0 release notes under breaking changes.
Thanks for pointing this out!
