### ISSUE TITLE
Annotation processor gives FATAL ERROR: picocli.CommandLine$InitializationException: ArgGroup has no options or positional parameters, and no subgroups

### ISSUE THREAD

**Issue by remkop** [remkop/picocli#794]
(Related to https://github.com/remkop/picocli/issues/793) The annotation processor occasionally gives this error for composite groups:

```
FATAL ERROR: picocli.CommandLine$InitializationException: ArgGroup has no options or positional parameters, and no subgroups
```

This is not easy to reproduce but may happen when building from Gradle or when an arg group is used as both a field and as a parameter in a `@Command`-annotated method.

The cause is likely that the annotation processor depends on the `javac` compiler to present `@ArgGroup`-annotated elements in topologically sorted order (so the groups with no dependencies on other groups come first, and groups that depend on other groups come later). 

When this assumption is broken, the above error may occur if a composite arg group is built before its subgroups are built.

The solution is for the annotation processor to do its own topological sorting and not depend on javac.

**Comment by antonmry** [comment]
This is hitting me when launching picocli 4.2.0 from IntelliJ Idea, even with Annotation Processor enabled. It works well compiling and launch it from the terminal.

```
Error:java: FATAL ERROR: picocli.CommandLine$InitializationException: ArgGroup has no options or positional parameters, and no subgroups: null AnnotatedElementHolder(FIELD configGroup in KtmSanityCheck)
  	at picocli.CommandLine$Model$ArgGroupSpec.<init>(CommandLine.java:8655)
  	at picocli.CommandLine$Model$ArgGroupSpec$Builder.build(CommandLine.java:9082)
  	at picocli.codegen.annotation.processing.AbstractCommandSpecProcessor$Context.connectArgGroups(AbstractCommandSpecProcessor.java:954)
  	at picocli.codegen.annotation.processing.AbstractCommandSpecProcessor$Context.connectModel(AbstractCommandSpecProcessor.java:832)
  	at picocli.codegen.annotation.processing.AbstractCommandSpecProcessor$Context.access$000(AbstractCommandSpecProcessor.java:783)
  	at picocli.codegen.annotation.processing.AbstractCommandSpecProcessor.tryProcess(AbstractCommandSpecProcessor.java:185)
  	at picocli.codegen.annotation.processing.AbstractCommandSpecProcessor.process(AbstractCommandSpecProcessor.java:156)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:802)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:713)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1043)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1184)
  	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
  	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
  	at com.sun.tools.javac.main.Main.compile(Main.java:523)
  	at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
  	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
  	at org.jetbrains.jps.javac.JavacMain.compile(JavacMain.java:207)
  	at org.jetbrains.jps.incremental.java.JavaBuilder.compileJava(JavaBuilder.java:486)
  	at org.jetbrains.jps.incremental.java.JavaBuilder.compile(JavaBuilder.java:338)
  	at org.jetbrains.jps.incremental.java.JavaBuilder.doBuild(JavaBuilder.java:263)
  	at org.jetbrains.jps.incremental.java.JavaBuilder.build(JavaBuilder.java:216)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.runModuleLevelBuilders(IncProjectBuilder.java:1328)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.runBuildersForChunk(IncProjectBuilder.java:1006)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.buildTargetsChunk(IncProjectBuilder.java:1073)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.buildChunkIfAffected(IncProjectBuilder.java:967)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.buildChunks(IncProjectBuilder.java:796)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.runBuild(IncProjectBuilder.java:378)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.build(IncProjectBuilder.java:178)
  	at org.jetbrains.jps.cmdline.BuildRunner.runBuild(BuildRunner.java:140)
  	at org.jetbrains.jps.cmdline.BuildSession.runBuild(BuildSession.java:297)
  	at org.jetbrains.jps.cmdline.BuildSession.run(BuildSession.java:130)
  	at org.jetbrains.jps.cmdline.BuildMain$MyMessageHandler.lambda$channelRead0$0(BuildMain.java:232)
  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  	at java.lang.Thread.run(Thread.java:748)

```

**Comment by remkop** [comment]
Recently I occasionally encounter this in intelli/j.  I’ve been able to resolve it by specifying a different JDK than the one that’s built-in to Intelli/J. 

Are you using Intelli/J?

**Comment by antonmry** [comment]
Yes, using IntelliJ Idea 2019.3 with a separate JDK 1.8.0_141. The error happens when we add a second subcommand with Annotation Processors enabled.

**Comment by remkop** [comment]
Ok, that is interesting. Can you provide your command(s) so I can try to reproduce it?

**Comment by antonmry** [comment]
It's a quite big application, these are the relevant parts:

KtmCli.java:

```java
@Command(name = "ktm-cli", description = "xxx",
    version = KtmCli.PROJECT_VERSION, subcommands = {KtmTopic.class, KtmSanityCheck.class}
)
@Slf4j
public class KtmCli {
}
```

KtmTopic.java:

```java
@Command(name = "topic", description = "yyyy",
    mixinStandardHelpOptions = true, exitCodeListHeading = "Exit Codes:%n",
    exitCodeList = {EXIT_SUCCESS + ": successful program execution",
        EXIT_ERROR_CONFIG_CLIENT + ": error in config client",
        EXIT_ERROR_CONFIG_TOPIC + ": error in config topic", EXIT_ERROR_GENERIC + ": error in execution time"})
@Slf4j
public class KtmTopic implements Callable<Integer> {

    @ArgGroup(exclusive = ActionGroup.EXCLUSIVE, multiplicity = "0..1", heading = "\n" + ActionGroup.GROUP_KEY + ":\n")
    private ActionGroup actionGroup;

    @ArgGroup(exclusive = ConfigGroup.EXCLUSIVE, multiplicity = "0..1", heading = "\n" + ConfigGroup.GROUP_KEY + ":\n")
    private ConfigGroup configGroup;

    @ArgGroup(exclusive = LogGroup.EXCLUSIVE, multiplicity = "0..1", heading = "\n" + LogGroup.GROUP_KEY + ":\n")
    private LogGroup logGroup;

    @ArgGroup(exclusive = TopicGroup.EXCLUSIVE, multiplicity = "1", heading = "\n" + TopicGroup.GROUP_KEY + ":\n")
    private TopicGroup topicGroup;

```


KtmSanityCheck.java:

```java
@Command(name = "sanity", description = "zzzzz",
        mixinStandardHelpOptions = true, exitCodeListHeading = "Exit Codes:%n",
        exitCodeList = {EXIT_SUCCESS + ": successful program execution",
                EXIT_ERROR_CONFIG_CLIENT + ": error in config client"})
@Slf4j
public class KtmSanityCheck implements Callable<Integer> {

    @ArgGroup(exclusive = ConfigGroup.EXCLUSIVE, multiplicity = "0..1", heading = "\n" + ConfigGroup.GROUP_KEY + ":\n")
    private ConfigGroup configGroup;

    @ArgGroup(exclusive = LogGroup.EXCLUSIVE, multiplicity = "0..1", heading = "\n" + LogGroup.GROUP_KEY + ":\n")
    private LogGroup logGroup;

```

**Comment by hatyo** [comment]
I am consistently hitting this issue on IntelliJ. I have a (root)command and a bunch of subcommands separated in different files, one of these subcommmands contain two `ArgGroup` groups.

Interestingly, if I modify something the Java file of the root command and try to rebuild, I consistently get this error:

```
Error:java: FATAL ERROR: picocli.CommandLine$InitializationException: ArgGroup has no options or positional parameters, and no subgroups: AnnotatedElementHolder(FIELD tableNameGroup in a.b.c.RowCommand) in null
  	at picocli.CommandLine$Model$ArgGroupSpec.<init>(CommandLine.java:9449)
  	at picocli.CommandLine$Model$ArgGroupSpec$Builder.build(CommandLine.java:9893)
  	at picocli.codegen.annotation.processing.AbstractCommandSpecProcessor$Context.connectArgGroups(AbstractCommandSpecProcessor.java:954)
  	at picocli.codegen.annotation.processing.AbstractCommandSpecProcessor$Context.connectModel(AbstractCommandSpecProcessor.java:832)
  	at picocli.codegen.annotation.processing.AbstractCommandSpecProcessor$Context.access$000(AbstractCommandSpecProcessor.java:783)
  	at picocli.codegen.annotation.processing.AbstractCommandSpecProcessor.tryProcess(AbstractCommandSpecProcessor.java:185)
  	at picocli.codegen.annotation.processing.AbstractCommandSpecProcessor.process(AbstractCommandSpecProcessor.java:156)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
  	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
  	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
  	at com.sun.tools.javac.main.Main.compile(Main.java:523)
  	at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
  	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
  	at org.jetbrains.jps.javac.JavacMain.compile(JavacMain.java:207)
  	at org.jetbrains.jps.incremental.java.JavaBuilder.compileJava(JavaBuilder.java:486)
  	at org.jetbrains.jps.incremental.java.JavaBuilder.compile(JavaBuilder.java:338)
  	at org.jetbrains.jps.incremental.java.JavaBuilder.doBuild(JavaBuilder.java:263)
  	at org.jetbrains.jps.incremental.java.JavaBuilder.build(JavaBuilder.java:216)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.runModuleLevelBuilders(IncProjectBuilder.java:1328)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.runBuildersForChunk(IncProjectBuilder.java:1006)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.buildTargetsChunk(IncProjectBuilder.java:1073)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.buildChunkIfAffected(IncProjectBuilder.java:967)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.buildChunks(IncProjectBuilder.java:796)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.runBuild(IncProjectBuilder.java:378)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.build(IncProjectBuilder.java:178)
  	at org.jetbrains.jps.cmdline.BuildRunner.runBuild(BuildRunner.java:140)
  	at org.jetbrains.jps.cmdline.BuildSession.runBuild(BuildSession.java:297)
  	at org.jetbrains.jps.cmdline.BuildSession.run(BuildSession.java:130)
  	at org.jetbrains.jps.cmdline.BuildMain$MyMessageHandler.lambda$channelRead0$0(BuildMain.java:232)
  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  	at java.lang.Thread.run(Thread.java:748)
```

However, if I modify anything in the Java file of the subcommand with the two `ArgGroup`s, it compiles correctly.

IntelliJ version: 2019.3.5
JDK: 1.8.0.251
picocli version: 4.4.0

**Comment by remkop** [comment]
@hatyo I still occasionally see this error when a project is incrementally compiled in Intelli/J. 
When I do Rebuild Project in intelli/J the project compiles correctly without any error. 
(I don't remember if this particular project has the `picocli-codegen` annotation processor configured.)

Is this your experience too?

It may be an issue of intelli/J's incremental compilation and may not be a problem in picocli. 
However, if you can share a way for me to reproduce the problem I will try to investigate.

**Comment by remkop** [comment]
@hatyo I was able to reproduce the error.
Since this ticket is closed, I created a new one https://github.com/remkop/picocli/issues/1138 to investigate.

**Comment by remkop** [comment]
[Picocli 4.5](https://github.com/remkop/picocli/releases/tag/v4.5.0) has been released, which includes this fix.
