### ISSUE TITLE
Only multi-value options should have a split regex

### ISSUE THREAD

**Issue by bootstraponline** [remkop/picocli#834]
I'm updating picocli for Flank and am getting these long stack traces:

- [Main.kt](https://github.com/TestArmada/flank/blob/master/test_runner/src/main/kotlin/ftl/Main.kt) 

It's not obvious where the problem is or what the suggested fix is.

```
$ flank
Exception in thread "main" picocli.CommandLine$InitializationException: Only multi-value options and positional parameters should have a split regex (this check can be disabled by setting system property 'picocli.ignore.invalid.split')
	at picocli.CommandLine$Model$ArgSpec.<init>(CommandLine.java:7108)
	at picocli.CommandLine$Model$ArgSpec.<init>(CommandLine.java:7015)
	at picocli.CommandLine$Model$OptionSpec.<init>(CommandLine.java:7944)
	at picocli.CommandLine$Model$OptionSpec.<init>(CommandLine.java:7919)
	at picocli.CommandLine$Model$OptionSpec$Builder.build(CommandLine.java:8090)
	at picocli.CommandLine$Model$CommandReflection.buildArgForMember(CommandLine.java:9770)
	at picocli.CommandLine$Model$CommandReflection.initFromAnnotatedTypedMembers(CommandLine.java:9686)
	at picocli.CommandLine$Model$CommandReflection.initFromAnnotatedFields(CommandLine.java:9639)
	at picocli.CommandLine$Model$CommandReflection.extractCommandSpec(CommandLine.java:9544)
	at picocli.CommandLine$Model$CommandSpec.forAnnotatedObject(CommandLine.java:5116)
	at picocli.CommandLine.<init>(CommandLine.java:223)
	at picocli.CommandLine.toCommandLine(CommandLine.java:3212)
	at picocli.CommandLine.access$12900(CommandLine.java:145)
	at picocli.CommandLine$Model$CommandReflection.initSubcommands(CommandLine.java:9610)
	at picocli.CommandLine$Model$CommandReflection.extractCommandSpec(CommandLine.java:9541)
	at picocli.CommandLine$Model$CommandSpec.forAnnotatedObject(CommandLine.java:5116)
	at picocli.CommandLine.<init>(CommandLine.java:223)
	at picocli.CommandLine.toCommandLine(CommandLine.java:3212)
	at picocli.CommandLine.access$12900(CommandLine.java:145)
	at picocli.CommandLine$Model$CommandReflection.initSubcommands(CommandLine.java:9610)
	at picocli.CommandLine$Model$CommandReflection.extractCommandSpec(CommandLine.java:9541)
	at picocli.CommandLine$Model$CommandSpec.forAnnotatedObject(CommandLine.java:5116)
	at picocli.CommandLine.<init>(CommandLine.java:223)
	at picocli.CommandLine.toCommandLine(CommandLine.java:3212)
	at picocli.CommandLine.access$12900(CommandLine.java:145)
	at picocli.CommandLine$Model$CommandReflection.initSubcommands(CommandLine.java:9610)
	at picocli.CommandLine$Model$CommandReflection.extractCommandSpec(CommandLine.java:9541)
	at picocli.CommandLine$Model$CommandSpec.forAnnotatedObject(CommandLine.java:5116)
	at picocli.CommandLine.<init>(CommandLine.java:223)
	at picocli.CommandLine.toCommandLine(CommandLine.java:3212)
	at picocli.CommandLine.access$12900(CommandLine.java:145)
	at picocli.CommandLine$Model$CommandReflection.initSubcommands(CommandLine.java:9610)
	at picocli.CommandLine$Model$CommandReflection.extractCommandSpec(CommandLine.java:9541)
	at picocli.CommandLine$Model$CommandSpec.forAnnotatedObject(CommandLine.java:5116)
	at picocli.CommandLine.<init>(CommandLine.java:223)
	at picocli.CommandLine.<init>(CommandLine.java:196)
	at ftl.Main$Companion.main(Main.kt:41)
	at ftl.Main.main(Main.kt)
```

**Comment by bootstraponline** [comment]
```diff
- implementation("info.picocli:picocli:4.0.0-beta-2")
+ implementation("info.picocli:picocli:4.0.4")
```

This looks like a recent check? The CLI is crashing now due to the warning.

**Comment by bootstraponline** [comment]
The issue ended up being `split = ",",` was used on an option that took only one value. Searching for all instances of split in the codebase helped me track down the offending options.

```diff
@Option(
        names = ["--smart-flank-gcs-path"],
-        split = ",",
        description = ["Google cloud storage path to save test timing data used by smart flank."]
    )
    var smartFlankGcsPath: String? = null
```
