### ISSUE TITLE
Annotation processor does not generate GraalVM config files for Kotlin (was: picocli.CommandLine$InitializationException)

### ISSUE THREAD

**Issue by bric3** [remkop/picocli#886]
Hi, I have an issue with Picocli and codegen, in the context of micronaut, kotlin and graalvm.

The native image fails to instantiate the command and output this exception :

```
$ ./mycli
16:47:50.964 [main] INFO  i.m.context.env.DefaultEnvironment - Established active environments: [cli]
Exception in thread "main" picocli.CommandLine$InitializationException: Could not instantiate class mycli.MyCommand: java.lang.NoSuchMethodException: mycli.MyCommand.<init>()
        at picocli.CommandLine$DefaultFactory.create(CommandLine.java:4841)
        at picocli.CommandLine$Model$CommandReflection.getOrCreateInstance(CommandLine.java:9709)
        at picocli.CommandLine$Model$CommandReflection.extractCommandSpec(CommandLine.java:9652)
        at picocli.CommandLine$Model$CommandSpec.forAnnotatedObject(CommandLine.java:5211)
        at picocli.CommandLine.<init>(CommandLine.java:223)
        at picocli.CommandLine.run(CommandLine.java:2870)
        at picocli.CommandLine.run(CommandLine.java:2795)
        at io.micronaut.configuration.picocli.PicocliRunner.run(PicocliRunner.java:139)
        at io.micronaut.configuration.picocli.PicocliRunner.run(PicocliRunner.java:117)
        at mycli.MyCommand$Companion.main(MyCommand.kt:122)
        at mycli.MyCommand.main(MyCommand.kt)
Caused by: java.lang.NoSuchMethodException: mycli.MyCommand.<init>()
        at java.lang.Class.getConstructor0(DynamicHub.java:3349)
        at java.lang.Class.getDeclaredConstructor(DynamicHub.java:2553)
        at picocli.CommandLine$DefaultFactory.create(CommandLine.java:4817)
        at io.micronaut.configuration.picocli.MicronautFactory.create(MicronautFactory.java:74)
        at picocli.CommandLine$DefaultFactory.create(CommandLine.java:4840)
        ... 10 more
```

I'm not sure  what I'm doing wrong after following both [micronaut guide](https://guides.micronaut.io/micronaut-creating-first-graal-app/guide/index.html#creatingGraalImage) and [picocli-codegen guide](https://github.com/remkop/picocli/tree/master/picocli-codegen).

From the guide the codegen annotation processor is supposed to generate a file there : `META-INF/native-image/picocli-generated/$project`, but when exploring the `build` folder, or the assembled jar file, the file is not present. 

_Could it be because kotlin is not well supported ?_

----

Tools in the shell 
* GraalVM 19.3.0-java 11
* Gradle 6.0.1

```gradle
plugins {
    id "io.spring.dependency-management"
    id "org.jetbrains.kotlin.jvm"
    id "org.jetbrains.kotlin.kapt"
    id "org.jetbrains.kotlin.plugin.allopen"
    id "com.github.johnrengelman.shadow"
    id "application"
}


version "0.1"
group "mycli"

repositories {
    mavenCentral()
    jcenter()
}

dependencyManagement {
    imports {
        // https://search.maven.org/artifact/io.micronaut/micronaut-bom/1.2.0/pom
        mavenBom("io.micronaut:micronaut-bom:${micronautVersion}") {
            bomProperties([
                    'junit5.version'          : junitVersion,
                    'picocli.version'         : picocliVersion,
                    'jackson.version'         : jacksonVersion,
                    'jackson.modules.version' : jacksonVersion,
                    'jackson.datatype.version': jacksonVersion
            ])
        }
    }
}

configurations {
    // for dependencies that are needed for development only
    developmentOnly
}

dependencies {
    annotationProcessor "io.micronaut.configuration:micronaut-picocli"
    annotationProcessor "info.picocli:picocli-codegen:${picocliVersion}"
    implementation("io.micronaut:micronaut-runtime")
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8:${kotlinVersion}")
    implementation("org.jetbrains.kotlin:kotlin-reflect:${kotlinVersion}")
    implementation("info.picocli:picocli")
    implementation("io.micronaut.configuration:micronaut-picocli")
    implementation("org.fusesource.jansi:jansi:${jansiVersion}")

    kapt("io.micronaut:micronaut-inject-java")
    kapt("io.micronaut:micronaut-validation")
    kaptTest("io.micronaut:micronaut-inject-java")

    runtimeOnly("com.fasterxml.jackson.module:jackson-module-kotlin")
    runtimeOnly("ch.qos.logback:logback-classic:${logbackVersion}")

    // micraunaut graalvm-native-image
    compileOnly "com.oracle.substratevm:svm"
    annotationProcessor "io.micronaut:micronaut-graal"

    testAnnotationProcessor("io.micronaut:micronaut-inject-java")
    testImplementation("org.assertj:assertj-core:${assertjVersion}")
    testImplementation("org.junit.jupiter:junit-jupiter-api")
    testImplementation("io.micronaut.test:micronaut-test-junit5")
    testImplementation("io.micronaut:micronaut-inject-java")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine")
}

test.classpath += configurations.developmentOnly
mainClassName = "mycli.MyCommand"

java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}

tasks.withType(JavaCompile) {
    options.encoding = "UTF-8"
    options.compilerArgs.addAll(["--release", "11", "-parameters", "-Aproject=${project.group}/${project.name}"])
}

jar {
    manifest {
        attributes(
                'Main-Class': mainClassName,
                'Implementation-Title': rootProject.name,
                'Implementation-Version': rootProject.version
        )
    }
}

test {
    useJUnitPlatform()
}

allOpen {
    annotation("io.micronaut.aop.Around")
}

compileKotlin {
    kotlinOptions {
        jvmTarget = '1.8'
        //Will retain parameter names for Java reflection
        javaParameters = true
    }
}

compileTestKotlin {
    kotlinOptions {
        jvmTarget = '1.8'
        javaParameters = true
    }
}

shadowJar {
    mergeServiceFiles()
//    archiveClassifier = 'shadow'
    archiveClassifier = ''
    archiveBaseName = rootProject.name
}

run.classpath += configurations.developmentOnly
run.jvmArgs('-noverify', '-XX:TieredStopAtLevel=1', '-Dcom.sun.management.jmxremote')

distTar.enabled = false
distZip.enabled = false
shadowDistTar.enabled = false
shadowDistZip.enabled = false

```

```gradle
pluginManagement {
    plugins {
        id "io.spring.dependency-management" version "${springDepManagementPluginVersion}"
        id "org.jetbrains.kotlin.jvm" version "${kotlinVersion}"
        id "org.jetbrains.kotlin.kapt" version "${kotlinVersion}"
        id "org.jetbrains.kotlin.plugin.allopen" version "${kotlinVersion}"
        id "com.github.johnrengelman.shadow" version "${shadowPluginVersion}"
    }
}

rootProject.name="mycli"
```

```properties
# gradle options
org.gradle.warning.mode=all
org.gradle.caching=true
org.gradle.parallel=true
# plugin versions
springDepManagementPluginVersion=1.0.8.RELEASE
depUpdatesPluginVersion=0.27.0
shadowPluginVersion=5.2.0
# dependencies versions
micronautVersion=1.2.6
kotlinVersion=1.3.61
junitVersion=5.5.2
assertjVersion=3.14.0
picocliVersion=4.1.1
jacksonVersion=2.10.1
jansiVersion=1.18
logbackVersion=1.2.3
```

```
./gradlew --console=verbose clean assemble
native-image --no-server -cp build/libs/mycli-*.jar
```

```kotlin
package mycli

import io.micronaut.configuration.picocli.PicocliRunner
import picocli.AutoComplete
import picocli.CommandLine.Command
import picocli.CommandLine.Parameters
import java.io.File
import java.util.concurrent.atomic.AtomicLong


@Command(name = "mycli",
         header = [
             "@|green my first cli |@"
         ],
         description = ["do something with a file],
         mixinStandardHelpOptions = true,
         versionProvider = ManifestVersionProvider::class,
         subcommands = [AutoComplete.GenerateCompletion::class])
class MyCommand : Runnable {
    @Parameters(description = ["file location"],
                paramLabel = "file")
    lateinit var hPath: File

    override fun run() {
        println("Parsing the file file '$hPath'")
        println()
    }

    companion object {
        @JvmStatic
        fun main(args: Array<String>) {
            PicocliRunner.run(MyCommand::class.java, *args)
        }
    }
}
```

**Comment by remkop** [comment]
Thank you for the detailed issue report!

Micronaut's annotation processing is more sophisticated than picocli's since it can handle Java, Kotlin and Groovy annotations.

Picocli's annotation processor currently does not use Kapt, and I am guessing that standard Java annotation processors cannot handle Kotlin annotations. I will look into improving this in the future.

Meanwhile, to allow you to create native images, please create a task in your Gradle build that runs picocli's `ReflectionConfigGenerator`. The `picocli-codegen` readme [shows how to do this](https://github.com/remkop/picocli/tree/master/picocli-codegen#gradle-1).

**Comment by bric3** [comment]
@remkop That did it, thanks a lot !!!!!

**Comment by remkop** [comment]
Glad to hear that!

**Comment by remkop** [comment]
My more recent understanding is that it should also be possible to fix this by replacing

```
    annotationProcessor "info.picocli:picocli-codegen:${picocliVersion}"
```

with

```
    kapt("info.picocli:picocli-codegen:${picocliVersion}")
```
