### ISSUE TITLE
No-arg methods annotated with @Command must be public

### ISSUE THREAD

**Issue by dconnelly** [remkop/picocli#905]
Methods annotated with `@Command` but without parameters must be public otherwise an illegal access exception occurs:
```
    java.lang.IllegalAccessException: class picocli.CommandLine cannot access a member of class io.dconnelly.TestCommand with modifiers ""
    	at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:361)
    	at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:591)
    	at java.base/java.lang.reflect.Method.invoke(Method.java:558)
    	at picocli.CommandLine.executeUserObject(CommandLine.java:1802)
    	at picocli.CommandLine.access$900(CommandLine.java:145)
    	at picocli.CommandLine$RunLast.handle(CommandLine.java:2141)
    	at picocli.CommandLine$RunLast.handle(CommandLine.java:2108)
    	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:1975)
    	at picocli.CommandLine.execute(CommandLine.java:1904)
```
It appears that `setAccessible(true)` is only called for methods with parameters in `MethodParam` but not for parameterless methods. Not sure if `createIfAnnotated` was supposed to handle this but that is not called for methods annotated with `@Command`.

**Comment by remkop** [comment]
Nice catch!!
Thanks for raising this! I haven’t looked in detail yet but it sounds like it should be easy to fix.

**Comment by remkop** [comment]
Sorry for the slow response. I have been able to reproduce the issue and I agree with your analysis.
Thanks again for raising this!

----
Note to self:

Test to reproduce the issue:
```java
// CommandMethodTest
    @Command
    static class Issue905ParentCommand implements Runnable {
        public void run() {}

        @Command
        private int parameterless() {
            return 23;
        }
    }

    @Test
    public void testIssue905ParameterlessCommandMethodsException() {
        int actual = new CommandLine(new Issue905ParentCommand()).execute("parameterless");
        assertEquals(23, actual);
    }
```

Fix:

```
Index: src/main/java/picocli/CommandLine.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- src/main/java/picocli/CommandLine.java	(date 1580266741660)
+++ src/main/java/picocli/CommandLine.java	(date 1580266741660)
@@ -9797,6 +9797,7 @@
                 if (userObject.isMethod()) {
                     Method method = (Method) command;
                     t.debug("Using method %s as command %n", method);
+                    method.setAccessible(true);
                     Command cmd = method.getAnnotation(Command.class);
                     result.updateCommandAttributes(cmd, factory);
                     injectSpecIntoVersionProvider(result, cmd, factory);
```

**Comment by remkop** [comment]
This is now fixed in master and will be included in the next release.

You can test by checking out the latest master and building with:

```
gradlew clean publishToMavenLocal
```

That should publish `picocli-4.2.0-SNAPSHOT` to your local .m2 Maven cache. You can then try this in a project that uses the `info.picocli:picocli:4.2.0-SNAPSHOT` dependency.

Feedback welcome!

**Comment by remkop** [comment]
@dconnelly, All,

[picocli 4.2.0](https://github.com/remkop/picocli/releases/tag/v4.2.0) has been released, including this fix. Enjoy!
