### ISSUE TITLE
Bump Spring Boot dependency to 2.2.2 to allow it to work under Java 13 (was: Spring.Boot integration does not work with Java 13)

### ISSUE THREAD

**Issue by svanacker** [remkop/picocli#910]
The root cause is known, you have to update to Spring.Boot 2.2, which supports Java 13. Spring.Boot currently only supports Java 12.

```
Caused by: org.springframework.core.NestedIOException: ASM ClassReader failed to parse class file - probably due to a new Java class file version that isn't supported yet: file [C:\dev\git\asys\tools\tools-git-synchronizer-cli-java\app\bin\main\fr\asys\tools\git\synchronizer\cli\GitSynchronizerCommand.class]; nested exception is java.lang.IllegalArgumentException: Unsupported class file major version 57
	at org.springframework.core.type.classreading.SimpleMetadataReader.<init>(SimpleMetadataReader.java:57) ~[spring-core-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.core.type.classreading.SimpleMetadataReaderFactory.getMetadataReader(SimpleMetadataReaderFactory.java:103) ~[spring-core-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.core.type.classreading.CachingMetadataReaderFactory.getMetadataReader(CachingMetadataReaderFactory.java:123) ~[spring-core-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider.scanCandidateComponents(ClassPathScanningCandidateComponentProvider.java:430) ~[spring-context-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	... 19 common frames omitted
Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 57
	at org.springframework.asm.ClassReader.<init>(ClassReader.java:184) ~[spring-core-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.asm.ClassReader.<init>(ClassReader.java:166) ~[spring-core-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.asm.ClassReader.<init>(ClassReader.java:152) ~[spring-core-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.asm.ClassReader.<init>(ClassReader.java:273) ~[spring-core-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.core.type.classreading.SimpleMetadataReader.<init>(SimpleMetadataReader.java:54) ~[spring-core-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	... 22 common frames omitted
```

**Comment by remkop** [comment]
Thank you for raising this. I’ll take a look as soon as I can.

**Comment by remkop** [comment]
Hi, 
I wanted to reproduce the problem, so I cloned your https://github.com/svanacker/tools-git-synchronizer-cli-java project and tried to build it on Java 14.

However, it fails with a different error:

```
C:\Users\remko\IdeaProjects\tools-git-synchronizer-cli-java\app>gradlew  --no-daemon clean build

java.lang.NoClassDefFoundError: Could not initialize class org.codehaus.groovy.vmplugin.v7.Java7
        at org.codehaus.groovy.vmplugin.VMPluginFactory.<clinit>(VMPluginFactory.java:43)
        at org.codehaus.groovy.reflection.GroovyClassValueFactory.<clinit>(GroovyClassValueFactory.java:35)
        at org.codehaus.groovy.reflection.ClassInfo.<clinit>(ClassInfo.java:107)
        at org.codehaus.groovy.reflection.ReflectionCache.getCachedClass(ReflectionCache.java:95)
        at org.codehaus.groovy.reflection.ReflectionCache.<clinit>(ReflectionCache.java:39)
        at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.registerMethods(MetaClassRegistryImpl.java:210)
        at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.<init>(MetaClassRegistryImpl.java:108)
        at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.<init>(MetaClassRegistryImpl.java:86)
        at groovy.lang.GroovySystem.<clinit>(GroovySystem.java:36)
        at org.codehaus.groovy.runtime.InvokerHelper.<clinit>(InvokerHelper.java:86)
        at groovy.lang.GroovyObjectSupport.getDefaultMetaClass(GroovyObjectSupport.java:59)
        at groovy.lang.GroovyObjectSupport.<init>(GroovyObjectSupport.java:32)
        at org.gradle.internal.extensibility.DefaultExtraPropertiesExtension.<init>(DefaultExtraPropertiesExtension.java:29)
        at org.gradle.internal.extensibility.DefaultConvention.<init>(DefaultConvention.java:49)
        at org.gradle.internal.extensibility.ExtensibleDynamicObject.<init>(ExtensibleDynamicObject.java:60)
        at org.gradle.internal.instantiation.generator.MixInExtensibleDynamicObject.<init>(MixInExtensibleDynamicObject.java:35)
        at org.gradle.initialization.DefaultSettings_Decorated.getAsDynamicObject(Unknown Source)
        at org.gradle.initialization.SettingsFactory.createSettings(SettingsFactory.java:58)
        at org.gradle.initialization.ScriptEvaluatingSettingsProcessor.process(ScriptEvaluatingSettingsProcessor.java:61)
        at org.gradle.initialization.PropertiesLoadingSettingsProcessor.process(PropertiesLoadingSettingsProcessor.java:38)
        at org.gradle.initialization.SettingsEvaluatedCallbackFiringSettingsProcessor.process(SettingsEvaluatedCallbackFiringSettingsProcessor.java:34)
        at org.gradle.initialization.RootBuildCacheControllerSettingsProcessor.process(RootBuildCacheControllerSettingsProcessor.java:36)
        at org.gradle.initialization.BuildOperationSettingsProcessor$2.call(BuildOperationSettingsProcessor.java:50)
        at org.gradle.initialization.BuildOperationSettingsProcessor$2.call(BuildOperationSettingsProcessor.java:47)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
        at org.gradle.initialization.BuildOperationSettingsProcessor.process(BuildOperationSettingsProcessor.java:47)
        at org.gradle.initialization.DefaultSettingsLoader.findSettingsAndLoadIfAppropriate(DefaultSettingsLoader.java:102)
        at org.gradle.initialization.DefaultSettingsLoader.findAndLoadSettings(DefaultSettingsLoader.java:45)
        at org.gradle.initialization.SettingsAttachingSettingsLoader.findAndLoadSettings(SettingsAttachingSettingsLoader.java:35)
        at org.gradle.internal.composite.CommandLineIncludedBuildSettingsLoader.findAndLoadSettings(CommandLineIncludedBuildSettingsLoader.java:34)
        at org.gradle.internal.composite.ChildBuildRegisteringSettingsLoader.findAndLoadSettings(ChildBuildRegisteringSettingsLoader.java:52)
        at org.gradle.internal.composite.CompositeBuildSettingsLoader.findAndLoadSettings(CompositeBuildSettingsLoader.java:35)
        at org.gradle.initialization.DefaultSettingsPreparer.prepareSettings(DefaultSettingsPreparer.java:36)
        at org.gradle.initialization.BuildOperatingFiringSettingsPreparer$LoadBuild.doLoadBuild(BuildOperatingFiringSettingsPreparer.java:59)
        at org.gradle.initialization.BuildOperatingFiringSettingsPreparer$LoadBuild.run(BuildOperatingFiringSettingsPreparer.java:54)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:92)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.initialization.BuildOperatingFiringSettingsPreparer.prepareSettings(BuildOperatingFiringSettingsPreparer.java:42)
        at org.gradle.initialization.DefaultGradleLauncher.prepareSettings(DefaultGradleLauncher.java:194)
        at org.gradle.initialization.DefaultGradleLauncher.doClassicBuildStages(DefaultGradleLauncher.java:138)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:130)
        at org.gradle.initialization.DefaultGradleLauncher.executeTasks(DefaultGradleLauncher.java:110)
        at org.gradle.internal.invocation.GradleBuildController$1.execute(GradleBuildController.java:60)
        at org.gradle.internal.invocation.GradleBuildController$1.execute(GradleBuildController.java:57)
        at org.gradle.internal.invocation.GradleBuildController$3.create(GradleBuildController.java:85)
        at org.gradle.internal.invocation.GradleBuildController$3.create(GradleBuildController.java:78)
        at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:189)
        at org.gradle.internal.work.StopShieldingWorkerLeaseService.withLocks(StopShieldingWorkerLeaseService.java:40)
        at org.gradle.internal.invocation.GradleBuildController.doBuild(GradleBuildController.java:78)
        at org.gradle.internal.invocation.GradleBuildController.run(GradleBuildController.java:57)
        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:31)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
        at org.gradle.launcher.exec.BuildOutcomeReportingBuildActionRunner.run(BuildOutcomeReportingBuildActionRunner.java:63)
        at org.gradle.tooling.internal.provider.ValidatingBuildActionRunner.run(ValidatingBuildActionRunner.java:32)
        at org.gradle.launcher.exec.BuildCompletionNotifyingBuildActionRunner.run(BuildCompletionNotifyingBuildActionRunner.java:39)
        at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner$3.call(RunAsBuildOperationBuildActionRunner.java:51)
        at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner$3.call(RunAsBuildOperationBuildActionRunner.java:45)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
        at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner.run(RunAsBuildOperationBuildActionRunner.java:45)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter$1.transform(InProcessBuildActionExecuter.java:50)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter$1.transform(InProcessBuildActionExecuter.java:47)
        at org.gradle.composite.internal.DefaultRootBuildState.run(DefaultRootBuildState.java:78)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:47)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:31)
        at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:42)
        at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:28)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:78)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:52)
        at org.gradle.tooling.internal.provider.SubscribableBuildActionExecuter.execute(SubscribableBuildActionExecuter.java:59)
        at org.gradle.tooling.internal.provider.SubscribableBuildActionExecuter.execute(SubscribableBuildActionExecuter.java:36)
        at org.gradle.tooling.internal.provider.SessionScopeBuildActionExecuter.execute(SessionScopeBuildActionExecuter.java:68)
        at org.gradle.tooling.internal.provider.SessionScopeBuildActionExecuter.execute(SessionScopeBuildActionExecuter.java:38)
        at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:37)
        at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:26)
        at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildActionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:43)
        at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildActionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:29)
        at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:60)
        at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:32)
        at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:55)
        at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:41)
        at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:48)
        at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:32)
        at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:68)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:39)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:27)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:35)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.create(ForwardClientInput.java:78)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.create(ForwardClientInput.java:75)
        at org.gradle.util.Swapper.swap(Swapper.java:38)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:75)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:50)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:63)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:82)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:52)
        at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:297)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
        at java.base/java.lang.Thread.run(Thread.java:832)
```

My version info looks like this:

```
C:\Users\remko\IdeaProjects\tools-git-synchronizer-cli-java\app>gradlew --version

------------------------------------------------------------
Gradle 6.0.1
------------------------------------------------------------

Build time:   2019-11-18 20:25:01 UTC
Revision:     fad121066a68c4701acd362daf4287a7c309a0f5

Kotlin:       1.3.50
Groovy:       2.5.8
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          14-ea (Oracle Corporation 14-ea+27-1339)
OS:           Windows 10 10.0 amd64
```

Is that different from what you are seeing?

**Comment by pzygielo** [comment]
> JVM:          14-ea (Oracle Corporation 14-ea+27-1339)

I guess due to [GROOVY-9211](https://issues.apache.org/jira/browse/GROOVY-9211) gradle does not support JDK14 yet (which is different issue than reported here).

**Comment by svanacker** [comment]
Hello, the bug was only on Java 13 ans Gradle 6.0 support it Welles

Best regards

Le mer. 1 janv. 2020 à 09:32, Piotrek Żygieło <notifications@github.com> a
écrit :

**Comment by remkop** [comment]
@svanacker Sorry I am down with influenza so only made slow progress on this.
I just built your project with Java 13 and it builds without any error.

This means I cannot reproduce the problem.  
Does this mean that there is nothing that needs to be done in picocli?

If there is work that needs to be done in picocli, can you provide a way for me to reproduce the problem?

**Comment by svanacker** [comment]
Hello, no problem ! The problem is when you start the application, it will
crash, but on the current repo, gradle is using java 12 and not java 13. I
will créate a branch with the problem and a Way to reproduce.

Best regards

Le jeu. 2 janv. 2020 à 07:54, Remko Popma <notifications@github.com> a
écrit :

**Comment by remkop** [comment]
That would be great, thanks! Please include the commands I need to execute to reproduce the issue. I only ran `gradlew clean build`, not sure if that’s sufficient to reproduce...

**Comment by svanacker** [comment]
Hello

I have created a branch on my github :

https://github.com/svanacker/tools-git-synchronizer-cli-java/tree/java13_problem


For the command, on master or on this branch, just launch "gradle build",
then "gradle run", you will see the following trace.

For me, the action to do is juste to update the spring.boot dependencies in
picocli to 2.2.2.RELEASE, because I already had this problem, and Spring
2.1 does only support Java 12, and Spring 2.2 offer the support of Java 13

2020-01-03 16:54:50.789  INFO 20084 --- [           main]
g.s.c.ToolsGitSynchronizerCliApplication : Starting
ToolsGitSynchronizerCliApplication on PC113 with PID 20084
(C:\dev\git\asys\tools\tools-git-synchronizer-cli-java\app\build\classes\java\main
started by stevan in
C:\dev\git\asys\tools\tools-git-synchronizer-cli-java\app)
2020-01-03 16:54:50.792  INFO 20084 --- [           main]
g.s.c.ToolsGitSynchronizerCliApplication : No active profile set, falling
back to default profiles: default
2020-01-03 16:54:50.918  WARN 20084 --- [           main]
s.c.a.AnnotationConfigApplicationContext : Exception encountered during
context initialization - cancelling refresh attempt:
org.springframework.beans.factory.BeanDefinitionStoreException: Failed to
read candidate component class: file
[C:\dev\git\asys\tools\tools-git-synchronizer-cli-java\app\build\classes\java\main\fr\asys\tools\git\synchronizer\cli\ToolsGitSynchronizerCliApplication.class];
nested exception is org.springframework.core.NestedIOException: ASM
ClassReader failed to parse class file - probably due to a new Java class
file version that isn't supported yet: file
[C:\dev\git\asys\tools\tools-git-synchronizer-cli-java\app\build\classes\java\main\fr\asys\tools\git\synchronizer\cli\ToolsGitSynchronizerCliApplication.class];
nested exception is java.lang.IllegalArgumentException: Unsupported class
file major version 57
2020-01-03 16:54:50.933 ERROR 20084 --- [           main]
o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanDefinitionStoreException: Failed to
read candidate component class: file
[C:\dev\git\asys\tools\tools-git-synchronizer-cli-java\app\build\classes\java\main\fr\asys\tools\git\synchronizer\cli\ToolsGitSynchronizerCliApplication.class];
nested exception is org.springframework.core.NestedIOException: ASM
ClassReader failed to parse class file - probably due to a new Java class
file version that isn't supported yet: file
[C:\dev\git\asys\tools\tools-git-synchronizer-cli-java\app\build\classes\java\main\fr\asys\tools\git\synchronizer\cli\ToolsGitSynchronizerCliApplication.class];
nested exception is java.lang.IllegalArgumentException: Unsupported class
file major version 57
        at
org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider.scanCandidateComponents(ClassPathScanningCandidateComponentProvider.java:454)
~[spring-context-5.1.8.RELEASE.jar:5.1.8.RELEASE]
        at
org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider.findCandidateComponents(ClassPathScanningCandidateComponentProvider.java:316)
~[spring-context-5.1.8.RELEASE.jar:5.1.8.RELEASE]
        at
org.springframework.context.annotation.ClassPathBeanDefinitionScanner.doScan(ClassPathBeanDefinitionScanner.java:275)
~[spring-context-5.1.8.RELEASE.jar:5.1.8.RELEASE]
        at
org.springframework.context.annotation.ComponentScanAnnotationParser.parse(ComponentScanAnnotationParser.java:132)
~[spring-context-5.1.8.RELEASE.jar:5.1.8.RELEASE]
        at
org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:287)
~[spring-context-5.1.8.RELEASE.jar:5.1.8.RELEASE]
        at
org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:242)
~[spring-context-5.1.8.RELEASE.jar:5.1.8.RELEASE]
        at
org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:199)
~[spring-context-5.1.8.RELEASE.jar:5.1.8.RELEASE]
        at
org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:167)
~[spring-context-5.1.8.RELEASE.jar:5.1.8.RELEASE]
        at
org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:315)
~[spring-context-5.1.8.RELEASE.jar:5.1.8.RELEASE]
        at
org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:232)
~[spring-context-5.1.8.RELEASE.jar:5.1.8.RELEASE]
        at
org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:275)
~[spring-context-5.1.8.RELEASE.jar:5.1.8.RELEASE]
        at
org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:95)
~[spring-context-5.1.8.RELEASE.jar:5.1.8.RELEASE]
        at
org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:705)
~[spring-context-5.1.8.RELEASE.jar:5.1.8.RELEASE]
        at
org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:531)
~[spring-context-5.1.8.RELEASE.jar:5.1.8.RELEASE]
        at
org.springframework.boot.SpringApplication.refresh(SpringApplication.java:742)
~[spring-boot-2.1.6.RELEASE.jar:2.1.6.RELEASE]
        at
org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:389)
~[spring-boot-2.1.6.RELEASE.jar:2.1.6.RELEASE]
        at
org.springframework.boot.SpringApplication.run(SpringApplication.java:311)
~[spring-boot-2.1.6.RELEASE.jar:2.1.6.RELEASE]
        at
org.springframework.boot.SpringApplication.run(SpringApplication.java:1213)
~[spring-boot-2.1.6.RELEASE.jar:2.1.6.RELEASE]
        at
org.springframework.boot.SpringApplication.run(SpringApplication.java:1202)
~[spring-boot-2.1.6.RELEASE.jar:2.1.6.RELEASE]
        at
fr.asys.tools.git.synchronizer.cli.ToolsGitSynchronizerCliApplication.main(ToolsGitSynchronizerCliApplication.java:47)
~[main/:na]
Caused by: org.springframework.core.NestedIOException: ASM ClassReader
failed to parse class file - probably due to a new Java class file version
that isn't supported yet: file
[C:\dev\git\asys\tools\tools-git-synchronizer-cli-java\app\build\classes\java\main\fr\asys\tools\git\synchronizer\cli\ToolsGitSynchronizerCliApplication.class];
nested exception is java.lang.IllegalArgumentException: Unsupported class
file major version 57
        at
org.springframework.core.type.classreading.SimpleMetadataReader.<init>(SimpleMetadataReader.java:57)
~[spring-core-5.1.8.RELEASE.jar:5.1.8.RELEASE]
        at
org.springframework.core.type.classreading.SimpleMetadataReaderFactory.getMetadataReader(SimpleMetadataReaderFactory.java:103)
~[spring-core-5.1.8.RELEASE.jar:5.1.8.RELEASE]
        at
org.springframework.core.type.classreading.CachingMetadataReaderFactory.getMetadataReader(CachingMetadataReaderFactory.java:123)
~[spring-core-5.1.8.RELEASE.jar:5.1.8.RELEASE]
        at
org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider.scanCandidateComponents(ClassPathScanningCandidateComponentProvider.java:430)
~[spring-context-5.1.8.RELEASE.jar:5.1.8.RELEASE]
        ... 19 common frames omitted
Caused by: java.lang.IllegalArgumentException: Unsupported class file major
version 57
        at org.springframework.asm.ClassReader.<init>(ClassReader.java:184)
~[spring-core-5.1.8.RELEASE.jar:5.1.8.RELEASE]
        at org.springframework.asm.ClassReader.<init>(ClassReader.java:166)
~[spring-core-5.1.8.RELEASE.jar:5.1.8.RELEASE]
        at org.springframework.asm.ClassReader.<init>(ClassReader.java:152)
~[spring-core-5.1.8.RELEASE.jar:5.1.8.RELEASE]
        at org.springframework.asm.ClassReader.<init>(ClassReader.java:273)
~[spring-core-5.1.8.RELEASE.jar:5.1.8.RELEASE]
        at
org.springframework.core.type.classreading.SimpleMetadataReader.<init>(SimpleMetadataReader.java:54)
~[spring-core-5.1.8.RELEASE.jar:5.1.8.RELEASE]

>
>

**Comment by remkop** [comment]
Thank you for creating that branch. I was able to reproduce the issue.

Until the next version of picocli is released, you can work around this issue by adding the following to your `gradle.build` file to enforce the use of the correct Spring version:

```
configurations.all {
    resolutionStrategy {
        force "org.springframework.boot:spring-boot-starter:2.2.2.RELEASE"
        force "org.springframework.boot:spring-boot-configuration-processor:2.2.2.RELEASE"
    }
}
```
