### ISSUE TITLE
When using codegen, is there a workaround for kotlin classes that extend from a parent?

### ISSUE THREAD

**Issue by hanzo2001** [remkop/picocli#931]
I am working with Kotlin and I wanted to pull off the procedure from the example at [https://picocli.info/picocli-on-graalvm.html](https://picocli.info/picocli-on-graalvm.html)

The following kotlin example works:

```kotlin
import picocli.CommandLine
import kotlin.system.exitProcess

@CommandLine.Command(
        name = "TestMain",
        version = ["TestMain-0.1.0"],
        mixinStandardHelpOptions = true, // add --help and --version options
        description = ["@|bold blah |@"],
        showDefaultValues = true
)
class TestMain constructor(): Runnable {
    @CommandLine.Option(
            names = ["--param"],
            required = false,
            description = ["..."]
    )
    protected var param = "blah"
    override fun run() {
        println("Did something: $a $b")
    }
}

fun main(args: Array<String>) { exitProcess(CommandLine(TestMain()).execute(*args)) }
```

the result is as follows:

```json
[
  {
    "name" : "com.imt.anaga.TestMain",
    "allDeclaredConstructors" : true,
    "allPublicConstructors" : true,
    "allDeclaredMethods" : true,
    "allPublicMethods" : true,
    "fields" : [
      { "name" : "param" }
    ]
  },
  {
    "name" : "picocli.CommandLine$AutoHelpMixin",
    "allDeclaredConstructors" : true,
    "allPublicConstructors" : true,
    "allDeclaredMethods" : true,
    "allPublicMethods" : true,
    "fields" : [
      { "name" : "helpRequested" },
      { "name" : "versionRequested" }
    ]
  }
]
```

However, as soon as I need to add a constructor parameter to `TestMain` I get the following error that is not very descriptive:

> Cannot instantiate com.imt.anaga.TestMain: the class has no constructor

```
picocli.CommandLine$InitializationException: Cannot instantiate com.imt.anaga.TestMain: the class has no constructor
	at picocli.CommandLine$DefaultFactory.create(CommandLine.java:4880)
	at picocli.CommandLine$Model$CommandUserObject.getInstance(CommandLine.java:10212)
	at picocli.CommandLine$Model$CommandSpec.userObject(CommandLine.java:5312)
	at picocli.codegen.aot.graalvm.ReflectionConfigGenerator$Visitor.visitCommandSpec(ReflectionConfigGenerator.java:194)
	at picocli.codegen.aot.graalvm.ReflectionConfigGenerator.generateReflectionConfig(ReflectionConfigGenerator.java:128)
	at picocli.codegen.aot.graalvm.ReflectionConfigGenerator$App.call(ReflectionConfigGenerator.java:101)
	at picocli.codegen.aot.graalvm.ReflectionConfigGenerator$App.call(ReflectionConfigGenerator.java:80)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1782)
	at picocli.CommandLine.access$900(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2149)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2143)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2107)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:1974)
	at picocli.CommandLine.execute(CommandLine.java:1903)
	at picocli.codegen.aot.graalvm.ReflectionConfigGenerator.main(ReflectionConfigGenerator.java:112)
Caused by: java.lang.NoSuchMethodException: com.imt.anaga.TestMain.<init>()
	at java.base/java.lang.Class.getConstructor0(Class.java:3350)
	at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2554)
	at picocli.CommandLine$DefaultFactory.create(CommandLine.java:4855)
	at picocli.CommandLine$DefaultFactory.create(CommandLine.java:4878)
	... 14 more
```

Is there any workaround for the `picocli-codegen` tool?
If this is a known limitation, is it documented?

**Comment by remkop** [comment]
The underlying problem is the same as in https://github.com/remkop/picocli/issues/930 .
Once `ReflectionConfigGenerator` accepts a custom factory, it becomes possible to work around this.
I will try to push a fix to master soon.

**Comment by remkop** [comment]
With current master, the following example works:

```kotlin
package picocli.examples.kotlin.factory

import picocli.CommandLine
import kotlin.system.exitProcess

@CommandLine.Command(
        name = "TestMain",
        version = ["TestMain-0.1.0"],
        mixinStandardHelpOptions = true, // add --help and --version options
        description = ["@|bold blah |@"],
        showDefaultValues = true
)
class Example(val initial: String) : Runnable {
    @CommandLine.Option(
            names = ["--param"],
            required = false,
            description = ["..."]
    )
    protected var param = "blah"
    override fun run() {
        println("Did something: $param $initial")
    }
}

fun main(args: Array<String>) { exitProcess(CommandLine(Example::class.java, MyCommandFactory()).execute(*args)) }
```

and this is the factory:

```kotlin
package picocli.examples.kotlin.factory

import picocli.CommandLine.defaultFactory
import picocli.CommandLine.IFactory

class MyCommandFactory: IFactory {
    override fun <K : Any?> create(cls: Class<K>?): K {
        println(cls)
        if (cls != null) {
            println("is cls an Example?")
            //if ((cls as Any) is Example) {
            if (cls == Example::class.java) {
                println("Give away rabbit!")
                return Example("Rabbit") as K
            } else {
                println("NO")
            }
        }
        return defaultFactory().create(cls)
    }
}
```

**Comment by hanzo2001** [comment]
Thank you for helping out with this and for clarifying the issue. If anyone comes across this same issue regarding why kotlin seems to misbehave, the explanation can be found at [https://github.com/remkop/picocli/issues/930#issuecomment-580040692](https://github.com/remkop/picocli/issues/930#issuecomment-580040692)

**Comment by remkop** [comment]
@hanzo2001 Glad I was able to help. 

Please star picocli on GitHub if you like the project.
