### ISSUE TITLE
AutoComplete generator fails if the class with parameters/options is an inner class

### ISSUE THREAD

**Issue by krzyk** [remkop/picocli#932]
Simplified example:
```
package com.example;

public class Main {
    public static class Options {
            @CommandLine.Option(names = "-w", description = "wait time between retries")
            int waitTime = 30;
    }
    public static void main(String[] args) {
        Options options = CommandLine.populateCommand(new Options(), args);
        if (options.usageHelpRequested) {
            CommandLine.usage(options, System.out);
            return;
        }
        System.out.println("using options: " + options);
    }
}
```

And in pom.xml:
```
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>exec-maven-plugin</artifactId>
        <version>1.6.0</version>
        <executions>
          <execution>
            <id>generate-autocompletion-script</id>
            <phase>package</phase>
            <goals>
              <goal>exec</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <executable>java</executable>
          <arguments>
            <argument>-Dpicocli.autocomplete.systemExitOnError</argument>
            <argument>-cp</argument>
            <classpath/>
            <argument>picocli.AutoComplete</argument>
            <argument>--force</argument><!-- overwrite if exists -->
            <argument>--completionScript</argument>
            <argument>${project.build.directory}/medicover_completion.sh</argument>
            <argument>com.example.Main.Options</argument><!-- replace with your class -->
          </arguments>
        </configuration>
      </plugin>
```

The above fails with error code `4`, and I see following stacktrace there:
```
java.lang.ClassNotFoundException: com.kirela.medicover.Main.Options
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:341)
        at picocli.AutoComplete$App.call(AutoComplete.java:155)
        at picocli.AutoComplete$App.call(AutoComplete.java:96)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1783)
        at picocli.CommandLine.access$900(CommandLine.java:145)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2141)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2108)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:1975)
        at picocli.CommandLine.execute(CommandLine.java:1904)
        at picocli.AutoComplete.main(AutoComplete.java:74)
```

When I change the Options class to a normal public class in another file everything works fine.

**Comment by remkop** [comment]
Have you tried making the inner class `static`?
(If the inner class is not static Java internally needs a reference to the outer class in order to construct an instance of the inner class.)

**Comment by krzyk** [comment]
Yes, sorry, my example was hand written and I forgot about `static`.
The issue is with `public static class` inside top level `public class`

**Comment by remkop** [comment]
Then, in your pom.xml you need to specify the name of the class with `$`:

```
<argument>com.example.Main$Options</argument>
```

**Comment by krzyk** [comment]
Ooops, you are right I completely forgot about that :)

**Comment by remkop** [comment]
Glad to hear that the problem is solved!
