### ISSUE TITLE
Using List.of()/Collections.emptyList() as default value results in exception

### ISSUE THREAD

**Issue by krzyk** [remkop/picocli#935]
When I use `List.of()` as a default value for a `Collection` and later try to set an option with a value I get UnsupportedOperationException.

This does not happen if I use `List.of(SOME_VALUE)` or `new ArrayList<>()`.

Example class:
```
public class Options {
    @CommandLine.Option(names = "-d", description = "doctors, valid: ${COMPLETION-CANDIDATES} (default: ${DEFAULT-VALUE})")
    Collection<Main.Doctor> doctors = List.of();
}
```

And when calling with option: `-d FIRST_LAST` I get exception:
```
[picocli INFO] Picocli version: 4.1.4, JVM: 14-ea (Oracle Corporation OpenJDK 64-Bit Server VM 14-ea+27-1339), OS: Linux 5.5.0-rc1 amd64
[picocli INFO] Parsing 2 command line args [-d, FIRST_LAST]
[picocli INFO] Adding [FIRST_LAST] to field java.util.Collection<com.kirela.medicover.Main$Doctor> com.kirela.medicover.Options.doctors for option -d
Exception in thread "main" picocli.CommandLine$ParameterException: UnsupportedOperationException: null while processing argument at or before arg[1] 'FIRST_LAST' in [-d, FIRST_LAST]: java.lang.UnsupportedOperationException
        at picocli.CommandLine$ParameterException.create(CommandLine.java:15219)
        at picocli.CommandLine$ParameterException.access$16600(CommandLine.java:15143)
        at picocli.CommandLine$Interpreter.parse(CommandLine.java:11182)
        at picocli.CommandLine$Interpreter.parse(CommandLine.java:11067)
        at picocli.CommandLine.parse(CommandLine.java:1294)
        at picocli.CommandLine.populateCommand(CommandLine.java:1237)
        at com.kirela.medicover.Main.main(Main.java:202)
Caused by: java.lang.UnsupportedOperationException
        at java.base/java.util.ImmutableCollections.uoe(ImmutableCollections.java:73)
        at java.base/java.util.ImmutableCollections$AbstractImmutableCollection.add(ImmutableCollections.java:77)
        at picocli.CommandLine$Interpreter.applyValuesToCollectionField(CommandLine.java:11898)
        at picocli.CommandLine$Interpreter.applyOption(CommandLine.java:11563)
        at picocli.CommandLine$Interpreter.processStandaloneOption(CommandLine.java:11455)
        at picocli.CommandLine$Interpreter.processArguments(CommandLine.java:11338)
        at picocli.CommandLine$Interpreter.parse(CommandLine.java:11176)
        ... 4 more
```

If I don't use `-d` option everything works fine, so I expect that the code assumes that an empty list is growable, but in case of List.of() it is not. Same happens when I use `Collections.emptyList()`.

**Comment by remkop** [comment]
Picocli will create an instance of the annotated `Collection` field only if the field value is `null`. If it is not `null`, picocli will simply add to that existing collection.

Perhaps this is not documented as well as it should be.
If you have suggestions on how to improve the section on [Arrays and Collections](https://picocli.info/#_arrays_and_collections), feedback welcome!

The solution is to ensure that the field value is not an unmodifiable collection. For example:

```java
@Option(/* ... */)
Collection<Main.Doctor> doctors = new ArrayList(List.of(A, B, C);)
```

**Comment by krzyk** [comment]
Actually I didn't look into the docs about collections, I just assumed that if it works with `List.of(A, B, C)` (which is immutable) it will work with `List.of()` (wrapping in e.g. `ArrayList` is not needed for non-empty List.of(...), which is strange).
