### ISSUE TITLE
disable.resources.config vs disable.resource.config

### ISSUE THREAD

**Issue by maxandersen** [remkop/picocli#951]
using `-Aproject=. -Adisable.proxy.config -Adisable.reflect.config -Adisable.resources.config`
gives me:

```
Note: ReflectConfigGen is not enabled
Note: ResourceConfigGen writing to: CLASS_OUTPUT/META-INF/native-image/picocli-generated/./resource-config.json
error: FATAL ERROR: java.lang.IllegalArgumentException: Invalid relative name: META-INF/native-image/picocli-generated/./resource-config.json
  	at jdk.compiler/com.sun.tools.javac.file.JavacFileManager.getFileForOutput(JavacFileManager.java:830)
  	at jdk.compiler/com.sun.tools.javac.processing.JavacFiler.createResource(JavacFiler.java:532)
  	at picocli.codegen.aot.graalvm.processor.ProcessorUtil.generate(ProcessorUtil.java:16)
  	at picocli.codegen.aot.graalvm.processor.AbstractGenerator.generate(AbstractGenerator.java:34)
  	at picocli.codegen.aot.graalvm.processor.AbstractCompositeGeneratorProcessor.handleCommands(AbstractCompositeGeneratorProcessor.java:41)
  	at picocli.codegen.annotation.processing.AbstractCommandSpecProcessor.tryProcess(AbstractCommandSpecProcessor.java:188)
  	at picocli.codegen.annotation.processing.AbstractCommandSpecProcessor.process(AbstractCommandSpecProcessor.java:156)
  	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:980)
  	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$DiscoveredProcessors$ProcessorStateIterator.runContributingProcs(JavacProcessingEnvironment.java:816)
  	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1220)
  	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1356)
  	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1258)
  	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:936)
  	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:311)
  	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:170)
  	at jdk.compiler/com.sun.tools.javac.Main.compile(Main.java:57)
  	at jdk.compiler/com.sun.tools.javac.Main.main(Main.java:43)
Note: ProxyConfigGen is not enabled
warning: The following options were not recognized by any processor: '[disable.resources.config]'
```

are the docs wrong about `disable.resources.config` being the right value?

looking in [code](https://github.com/remkop/picocli/blob/cf03015210db6e249d79524e626a2626bf5618e1/picocli-codegen/src/main/java/picocli/codegen/aot/graalvm/processor/ResourceConfigGen.java#L13) says its `disable.resource.config` ?

**Comment by remkop** [comment]
Darn! The docs are wrong. Sorry about that. Fixing this now.

**Comment by remkop** [comment]
I fixed the documentation. Thanks for raising this!
