### ISSUE TITLE
Avoid creating user object in Help constructor

### ISSUE THREAD

**Issue by remkop** [remkop/picocli#968]
This is a follow-up to https://github.com/remkop/picocli/issues/690
@Immueggpain reported that there are still cases where subcommands are instantiated unnecessarily.

When the usage help message is printed, a  `CommandLine.Help` instance is created for the main command, as well as for each of its subcommands. It turns out that the `CommandLine.Help` constructor instantiates the user object.

Code to reproduce the issue:

```java
@Command(name = "foo")
class Foo {
    public Foo() {
        throw new IllegalStateException("Don't instantiate me!");
    }
}
@Command(subcommands = Foo.class )
class Launcher implements Runnable {
    public static void main(String[] args) {
        new CommandLine(new Launcher()).execute(args);
    }
    public void run() {
        CommandLine.usage(this, System.out);
    }
}
```

This will show a stack trace like below, proving that the `Foo` instructor was invoked:

```
picocli.CommandLine$InitializationException: Could not instantiate class picocli.SubcommandTests$Foo: java.lang.reflect.InvocationTargetException
	at picocli.CommandLine$DefaultFactory.create(CommandLine.java:4948)
	at picocli.CommandLine$Model$CommandUserObject.getInstance(CommandLine.java:10364)
	at picocli.CommandLine$Model$CommandSpec.userObject(CommandLine.java:5386)
	at picocli.CommandLine$Help.<init>(CommandLine.java:13145)
	at picocli.CommandLine$DefaultHelpFactory.create(CommandLine.java:4823)
	at picocli.CommandLine$Help.addSubcommand(CommandLine.java:13224)
	at picocli.CommandLine$Help.addAllSubcommands(CommandLine.java:13210)
	at picocli.CommandLine$Help.<init>(CommandLine.java:13151)
	at picocli.CommandLine$DefaultHelpFactory.create(CommandLine.java:4823)
	at picocli.CommandLine.usage(CommandLine.java:2448)
	at picocli.CommandLine.usage(CommandLine.java:2404)
	at picocli.CommandLine.usage(CommandLine.java:2372)
	at picocli.SubcommandTests$Launcher.run(SubcommandTests.java:2156)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1773)
	at picocli.CommandLine.access$900(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2154)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2148)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2112)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:1979)
	at picocli.CommandLine.execute(CommandLine.java:1908)
	at picocli.SubcommandTests$Launcher.main(SubcommandTests.java:2152)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at picocli.CommandLine$DefaultFactory.create(CommandLine.java:4923)
	at picocli.CommandLine$DefaultFactory.create(CommandLine.java:4944)
	... 20 more
Caused by: java.lang.IllegalStateException: Don't instantiate me!
	at picocli.SubcommandTests$Foo.<init>(SubcommandTests.java:2137)
	... 26 more
```

I believe that the user object instantiation in the `Help` constructor is a mistake; probably a leftover from early-stage work on #690, where this instantiation was a workaround to allow getting default values for options for display in the usage help message. That problem was later solved a different way, but the original workaround was forgotten and never removed.

All tests still pass after the user object instantiation in the `Help` constructor is removed; I will go ahead and remove it.

**Comment by Immueggpain** [comment]
@remkop Thanks for the fix. I'll recheck the issue when the next picocli release comes out.
